#!/usr/bin/perl
#-------------------------------------------------+
#    [APM] This script was generated by amp.pl    |
#    [APM] Created time: 2016-04-27 14:29:28      |
#-------------------------------------------------+
=pod

=head1 Name

meta16S_report.pl

=head1 Synopsis

perl meta16S_report.pl [options] <pipe config file> <result dir>

=head1 Options

 -n STR    the report directory name, default use the result dir 
 -f STR    the report package format, support zip|bz2|gz|rar, default bz2

=head1 Feedback

 Author: Peng Ai
 Email : pai@genedenovo.com

=head1 Version

=head2 v1.0

Date: 2016-04-27 14:29:28

=cut

use strict;
use warnings;
use Getopt::Std;
use File::Basename qw/basename dirname/;
use FindBin qw/$Bin/;
use Cwd 'abs_path';

use lib "/home/aipeng/work/develepment/lib/";
use General qw/timeLOG/;

use lib "/Bio/User/aipeng/bin/report/lib";
use GDHR;

my %opts = (f=>"bz2");
getopts('n:f:e',\%opts);

die `pod2text $0` unless @ARGV == 2;

# set the public var 
our ($best_taxon);

# the config file to run meta16S pipe
my $conf_file = shift @ARGV;
my $conf = read_conf($conf_file);
my @samples = split /[;,\s\t]/ , $conf->{SamplesOrder};

# the last result dir of meta16S pipe which will be packed and compress.
my $outdir = shift @ARGV;

my $oname = basename($outdir);
my $resdir = dirname($outdir);

if ($opts{n})
{
	$oname = basename($opts{n});
	system("ln -sf $outdir $resdir/$oname");
	system("rm -f $outdir/upload") if (-e "$outdir/upload");
	$outdir = "$resdir/$oname";
}

# init the HTML report 
my $report = GDHR->new(-outdir=>$outdir,-pipe=>"$conf->{SequenceTitle} 高变区测序");

# 1. project basic information introduction
my $section = $report->section(id=>"project_info");
&project_info($section);

# 2. experiment and bioinformatic analysis flow introdunction
$section = $report->section(id=>"flows");
&create_tech_desc($section);

# 3. junior bioinformatic analysis 
$section = $report->section(id=>"junior");
&junior_analysis($section);

# 4. senior bioinformatic analysis of OTU
$section = $report->section(id=>"senior_OTU");
&senior_OTU($section);

# 5. senior bioinformatic analysis of Taxonomy
$section = $report->section(id=>"senior_taxon");
&senior_taxon($section);

# 6. different analysis (optional) 
if ($conf->{Group_diff_metastat} || $conf->{Group_diff_Lefse})
{
	$section = $report->section(id=>"different_analysis");
	&different_analysis($section);
}

# 7. result file tree structure 
$section = $report->section(id=>"data");
&data_save($section);

# 8. reference
$section = $report->section(id=>"reference");
&reference($section);

# 9. supplementary
$section = $report->section(id=>"supplementary");
&supplementary($section);

# create the html file and pack the result dir.
$report->write();

exit if ($opts{e});

# move the images and help doc html files to "src" directory
if (-d "$Bin/image")
{
	system("cp -rfL $Bin/image/* $outdir/src/image");
}

if (-d "$Bin/doc")
{
	system("cp -rfL $Bin/doc/* $outdir/src/doc");
}

# trans html report to pdf 
system("sh /Bio/Bin/pipe/meta/16s/report/html2pdf.sh $outdir/src/content.html $outdir/src/content.pdf");
timeLOG("the pdf report was created");

# create brief result
system("rm -rf $resdir/${oname}_brief; cp -rL $outdir $resdir/${oname}_brief");
&brief_result("$resdir/${oname}_brief");
timeLOG("the brief report was created");

if ($opts{f} eq "zip")
{
	system("cd $resdir; zip -r ${oname}_brief.zip ${oname}_brief");
}
elsif ($opts{f} eq "bz2")
{
	system("cd $resdir; tar -cjf ${oname}_brief.tar.bz2 ${oname}_brief");
}
elsif ($opts{f} eq "gz")
{
	system("cd $resdir; tar -czf ${oname}_brief.tar.gz ${oname}_brief");
}
elsif ($opts{f} eq "rar")
{
	system("cd $resdir; rar a -r ${oname}_brief.rar ${oname}_brief");
}
else 
{
	die("this package format is not support now, $opts{f} \n");
}

timeLOG("the brief report was packed");

# pack the report
$report->pack(-format=>$opts{f});

#------------------------------------------------
# sub function
#------------------------------------------------
sub project_info
{
	my $section = shift;
	my $line_num = 8;
	
	my $num = scalar @samples;
	
	my $sample_names;
	
	if ($num <= $line_num)
	{
		$sample_names .= join ("<span class=\"project_info_separator\">&brvbar;</span>", @samples);
	}
	else 
	{
		$line_num = int (($num-1)/((int( ($num-1)/$line_num) ) + 1)) + 1;
		my $i = 0;
		for ($i=0; $i < $num; $i+=$line_num )
		{
			if ($i + $line_num < $num)
			{
				my @tmp = map { $samples[$_] } $i .. $i + $line_num - 1;
				$sample_names .= join ("<span class=\"project_info_separator\">&brvbar;</span>", @tmp);
				$sample_names .= "\n\<br \/\>\n";
			}
			elsif ($i + $line_num >= $num)
			{
				my @tmp = map { $samples[$_] } $i .. $num - 1;
				$sample_names .= join ("<span class=\"project_info_separator\">&brvbar;</span>", @tmp);
			}
		}
	}
	
	my $groups = $conf->{groups};
	my $groups_info  = "";
	
	if ($groups && $groups ne "none")
	{
		$groups =~ s/\s+$//;
		$groups =~ s/^\s+//;
		my @groups = split /\s+/,$groups;
		my @groups_inner;
		foreach my$group(@groups)
		{
			my ($gname,$samples) = split /:/,$group;
			my @samples = split /,/,$samples;
			my $members = join "<span class=\"project_info_and\">\&</span>" , @samples;
			push @groups_inner , "<span class=\"project_info_group_lab\">$gname :</span>$members";
		}
		
		my $info = join "<span class=\"project_info_separator\">&brvbar;</span>" , @groups_inner;
		$groups_info = "<tr><td>分组方案</td><td>$info</td></tr>"
	}	
	
	my $project_info_tab = <<HTML;
<table>
<tr><td>项目编号</td><td>$conf->{"Project"}</td></tr>
<tr><td>测序区域</td><td>$conf->{"SequenceRegion"}</td></tr>
<tr><td>样品信息</td><td>$sample_names</td></tr>
$groups_info
</table>
HTML
	
	$section->menu("项目概述");
	$section->desc($project_info_tab);
}

sub create_tech_desc
{
	my $section = shift;
	
	my $primer_16s = qq(341F：<font color="red">CCTAYGGGRBGCASCAG</font>; 806R：<font color="red">GGACTACNNGGGTATCTAAT</font>);
	my $primer_ITS = qq(F：<font color="red">GCATCGATGAAGAACGCAGC</font>; R：<font color="red">ATATGTAGGATGAAGAACGYAGYRAA</font>);
	
	my $primer = $conf->{SequenceTitle} =~ /16s/ ? $primer_16s : $primer_ITS; 
	
	my $lab_desc = <<TEXT;
从样本中提取基因组DNA后，用带有barcode的特异引物扩增$conf->{SequenceTitle}的$conf->{SequenceRegion}区。引物序列为: 
<br />
${primer}。
<br />
然后PCR扩增产物切胶回收，用QuantiFluorTM荧光计进行定量。
将纯化的扩增产物进行等量混合，连接测序接头，构建测序文库，Hiseq2500 PE250上机测序。
TEXT
	
	my $analysis_desc = <<TEXT;
TEXT
	
	$section->menu("技术介绍");
	$section->submenu("实验流程");
	$section->img2html(-file=>"image/meta16S_lab_flow.png",-name=>"实验流程图",-desc=>$lab_desc);
	#$section->desc($lab_desc);
	$section->submenu("信息分析流程");
	$section->img2html(-file=>"image/meta16S_analysis_flow.png",-name=>"信息分析流程图",-desc=>$analysis_desc);
}

sub junior_analysis
{
	my $section = shift;
	my $num = scalar @samples;
	
	my $filter_desc = <<HTML;
<p>
测序得到的原始下机数据（raw data）包含一定的低质量数据等，会影响后续的分析，因此需要对原始下机数据进行过滤。过滤的条件如下：<br />
<ul>
<li>去除N比例过高的序列：去除reads中N碱基占比超过10%的序列</li>
<li>去除低质量序列：去除质量值高于20的碱基数占碱基总数的百分比小于80%的reads（碱基质量值的计算公式 <b>Q = -10•log10(e)</b>，碱基质量值小于20表示碱基错误率大于 1%）。</li>
</ul>
<br />
数据过滤得到clean data后，根据PE reads之间的重叠关系，将成对双端reads拼接为一条序列。拼接的条件是最小匹配长度为 10 bp，重叠区域允许的错配率为 0.02。
拼接得到的序列称为tag。<br /><br />
样本Tags的详细信息如下表所示.
<br /><br />
详细信息可查看文件: <a href="../1.tag/stat" target="_blank">1.tag/stat/</a>stat_tag.xls
</p>
HTML
	
	my $tag_stat_desc = <<TEXT;
说明：图中横坐标表示 tags 序列的长度，纵坐标表示某一特定长度时的 tag 序列的数量。
为便于作图，我们以0.1为阈值对横坐标上单个长度位点所有样品tag均不达标的长度位点进行了合并。
TEXT
	
	my $tag_abundance_desc = <<TEXT;
我们利用 Mothur<sup><a name="cite_back_1" href="#cite1">[1]</a></sup>(v.1.34.0)软件包对 tag 序列进行了去冗余处理，
从中挑选出 unique tag 序列（该序列实际是一组完全相同的 tag 序列的代表，
每一条 unique tag 都代表了数量不等的 tag 序列，每一条unique tag所代表的tag数即为该unique tag的丰度）。<br /><br />
去冗余之后的结果统计如下所示。
<br /><br />
详细信息可查看文件:<a href="../1.tag/stat" target="_blank">1.tag/stat/</a>stat_uniqTag.xls
TEXT
	
	my $last_num = `wc -l $outdir/1.tag/stat/tagAbdDistr`;
	chomp $last_num;
	$last_num --;
	my $tag_abundance_fig_desc = <<TEXT;
说明：图中横坐标是unique tag的丰度，丰度大于 $last_num 的 unique tags 数量计入丰度为 $last_num 的 unique tags 数量中；纵坐标是unique tag的数量。
TEXT
	
	my $rdp_opts = $conf->{TaxonamyOptions};
	my $rdp_confidence_cutoff = $rdp_opts =~ /-c\d*(\d+)/ ? $1 : 0.5;
	my $database   = $conf->{SequenceTitle} =~ /16S/i ? "Greengenes" : "UNITE";
	my $db_version = $conf->{SequenceTitle} =~ /16S/i ? "version 20101006" : "version 7.1";
	
	my $tags_taxon_desc = <<TEXT;
我们使用基于 Naive Bayesian 方法的分类器 rdp classifier<sup><a name="cite_back_2" href="#cite2">[2]</a></sup> 工具 ，对 tag 进行物种注释，该方法的优点为速度快，准确性高。
相对于其他方法，该方法的假阳性容易控制。 我们可以根据序列长度的变化，选择恰当的 Confidence Threshold(bootstrapping) 参数进行物种分类，
在本项目中我们使用的 Confidence Threshold 为 $rdp_confidence_cutoff。<br /><br />
物种注释所使用的物种分类数据库是：<b>$database<sup><a name="cite_back_3" href="#cite3">[3]</a></sup> ($db_version)</b>。<br /><br />
下面的截图显示了使用不同的 Confidence Threshold 时，将不同区域的序列分类到属上的注释率和准确率。
TEXT
	
	$section->menu("标准信息分析");
	$section->submenu("数据过滤及tags拼接");
	$section->add_html($filter_desc);
	$section->tsv2html(-file=>"$outdir/1.tag/stat/stat_tag.xls",-name=>"Tags 详细信息表",-header=>1,-top=>$num+1,-help=>"meta16S_help.html#tags-详细信息表");
	$section->img2html(-file=>"../1.tag/stat/tagLenDistr.png",-name=>"各样品Tags长度分布统计图",-desc=>$tag_stat_desc);
	
	$section->submenu("Tags 丰度统计");
	$section->desc($tag_abundance_desc);
	$section->tsv2html(-file=>"$outdir/1.tag/stat/stat_uniqTag.xls",-name=>"Unique Tags 详细信息表",-header=>1,-top=>$num+1,-help=>"meta16S_help.html#unique-tags-详细信息表");
	$section->img2html(-file=>"../1.tag/stat/tagAbdDistr.png",-name=>"各样品 tags 的丰度分布统计图",-desc=>$tag_abundance_fig_desc);
	
	$section->submenu("Tags 物种注释");
	$section->desc($tags_taxon_desc);
	$section->img2html(-file=>"image/classification_principle.jpg",-name=>"rdp参数选择说明");
	
}

sub senior_OTU
{
	my $section = shift;
	my $num = scalar @samples;
	
	my $otu_desc = <<TEXT;
为了更好地获得样品中物种的多样性信息我们首先对tags进行OTU(Operating Taxonomic Unit)聚类，我们利用 Mothur（v.1.34.0）计算0.03距离下（97%的相似度）的 OTU 数量，
如下表所示。
<br /><br />
详细信息查看表格文件：<a href="../2.otu/stat" target="_blank">2.otu/stat/</a>stat_otu.xls
TEXT
	
	my $last_num = `wc -l $outdir/2.otu/stat/otuAbdDistr`;
	chomp $last_num;
	$last_num --;
	my $otu_abudance_fig_desc = <<TEXT;
说明：图中横坐标为 OTU 丰度，丰度大于 $last_num 的 OTU 数量计入丰度为 $last_num 的 OTU 数量中；纵坐标为相应丰度下 OTU 的数量。
TEXT
	
	my $otu_taxon_desc = <<TEXT;
OTU 物种注释方法采用众数原则，首先统计该 OTU 中所有 tags 的物种注释信息，如果 66% 的 tags 都支持同一个物种分类单元，
那么该物种分类就作为该 OTU 的物种分类信息，否则则在递归到上一级分类单元进行统计，直到满足众数原则的要求。详细结果见OTU表达谱的数据。<br /><br />
物种分类单元（从上往下）：界->门->纲->目->科->属->种
TEXT
	
	my $otu_pathway_desc = <<TEXT;
所用软件：<b>PICRUSt<sup><a name="cite_back_4" href="#cite4">[4]</a></sup></b>
<br /><br />
PICRUSt(Phylogenetic Investigation of Communities by Reconstruction of Unobserved States)是一种通过标记基因和参考基因组数据库来预测样本数据的功能组成的计算方法。
<br /><br />
KEGG，全称Kyoto Encyclopedia of Genes and Genomes，是一个关于基因功能注释方面的综合性数据库，包括基因的功能，分类，代谢通路(KEGG Pathway数据库， 是KEGG最核心的数据库)等诸多方面的信息。
<br /><br />
KEGG Pathway数据库将生物代谢通路划分为6大类(A级分类)，分别为：新陈代谢（Metabolism）、遗传信息处理（Genetic Information Processing）、 
环境信息处理（Environmental Information Processing）、细胞过程（Cellular Processes）、生物体系统（Organismal Systems）、 人类疾病（Human Diseases），其中每大类又被系统分类为B、C、D3个级别。 其中B级分类目前包括有 43 种子功能；C级分类即为代谢通路图；D级分类为每个代谢通路图的具体注释信息。
TEXT
	
	my $tmp = $num + 1;
	my $tmp2 = $num + 2;
	my $otu_pathway_tab_desc = <<TEXT;
OTU Pathway注释信息如下表所示，表中第一列为注释到的Pathway的KO号，
第2列到第$tmp列是注释到该Pathway的OTU在各个样品中的丰度，第$tmp2列是KEGG的描述信息。
<br /><br />
详细信息查看表格文件：<a href="../2.otu/annot" target="_blank">2.otu/annot/</a>meta_ko_annot.xls
TEXT

	my @pathway_stat_imgs = map { "../2.otu/annot/Sample/$_.png" } @samples;
	my $pathway_stat_img_desc = <<TEXT;
说明：单个样品注释到的Pathway通路A、B级分类KO数量统计。
图中纵坐标为KEGG的A级和B级分类，黑色字体的是A级分类名，彩色字体的是B级分类名。横坐标为对应B级分类上OTU的数量。
TEXT
	
	my $otu_expr_desc = <<TEXT;
结合OTU的物种注释信息以及OTU在不同样品中的表达信息，我们得到包含所有样品的OTU的表达谱。
TEXT
	
	$tmp = $num + 1;
	$tmp2 = $tmp + 1;
	my $tmp3 = $tmp2 + $num - 1;
	my $tmp4 = $tmp3 + 1;
	my $otu_expr_tab_desc = <<TEXT;
OTU表达谱数据如下表所以，其中第1列为 OTU的ID，第2列到第$tmp列是OTU在$num个样品中所包含的tags数量，
第$tmp2列到第$tmp3列是OTU在$num个样品中的所包含的tags数量占各样品总tags数量的百分比，第$tmp4列往后为OTU在各个分类水平上的注释。
<br /><br />
详细信息查看表格文件：<a href="../2.otu/expression_profile" target="_blank">2.otu/expression_profile/</a>otu.profile.xls
TEXT
	
	my $otu_rarefaction_curve_desc = <<TEXT;
所用软件：Mothur（v.1.34.0）
<br /><br />
我们通过绘制稀释曲线（rarefaction curve）来评价测序量是否足以覆盖所有类群，并间接反映样品中物种的丰富程度。
稀释曲线是利用已测得序列中已知的 OTU 的相对比例，来计算抽取 n 个（n 小于测得 tags 序列总数）tags 时出现 OTU 数量的期望值，
然后根据一组 n 值（一般为一组小于总序列数的等差数列）与其相对应的 OTU 数量的期望值做出曲线来。
当曲线趋于平缓或者达到平台期时也就可以认为测序深度已经基本覆盖到样品中所有的物种。
TEXT
	
	my $otu_rarefaction_img_desc = <<TEXT;
说明: 图中横坐标表示抽取的 tags 数量；纵坐标表示抽取一定数量 tags 时所能得到 OTU 数量的期望值。 
TEXT
	
	my $otu_alpha_diversity_desc = <<HTML;
<p><span class="bold">所用软件：Mothur（v.1.34.0）</span></p>
<p><span class="bold">基于 OTU 的结果，我们计算了样品的 alpha 多样性，如 下表 所示。Alpha 多样性是对单个样品中物种多样性的分析，
包括 chao1 值、 ACE 值、Shannon 以及 Simpson 指数<sup><a name="cite_back_5" href="#cite5">[5]</a></sup>等。
chao1 和 ACE 两个多样性估算指数是根据所测得的 tags 数和 OTU 的数量以及相对比例来预测样品中微生物的种类（OTU 的数量），
是基于已知结果所得相对值。Shannon 指数是一个综合 OTU 丰度和 OTU 均匀度两方面因素的一个多样性指数，Shannon 及 npShannon 指数越大，
Simpson 指数越接近于 0，则表示该样品中的物种越丰富。 Simpson 指数有两种表示方法<sup><a name="cite_back_6" href="#cite6">[6]</a></sup>：
一种为 Simpson =Σ(Pi)<sup>2</sup>，另一种为 Simpson=1-Σ(Pi)<sup>2</sup>，其中 Pi 指第 i 个物种的个体数占群落中总个体数的比例，
两种表示方法中 Simpson 指数的取值范围均是 0≤Simpson≤1。本分析中采用第一种表示方法。</span></p>
<ul>
<li>chao1值的计算公式参见：<a href="http://www.mothur.org/wiki/Chao" target="_blank">http://www.mothur.org/wiki/Chao</a></li>
<li>ACE值的计算公式参见：<a href="http://www.mothur.org/wiki/Ace" target="_blank">http://www.mothur.org/wiki/Ace</a></li>
<li>shannon的计算公式参见：<a href="http://www.mothur.org/wiki/Shannon" target="_blank">http://www.mothur.org/wiki/Shannon</a></li>
<li>Simpson的计算公式参见：<a href="http://www.mothur.org/wiki/Simpson" target="_blank">http://www.mothur.org/wiki/Simpson</a></li>
<li>Npshannon的计算公式参见：<a href="http://www.mothur.org/wiki/Npshannon" target="_blank">http://www.mothur.org/wiki/Npshannon</a></li>
<li>Coverage的计算公式参见：<a href="http://www.mothur.org/wiki/Coverage" target="_blank">http://www.mothur.org/wiki/Coverage</a></li>
</ul>
HTML
	
	my $shannon_desc = <<HTML;
<p><span class="bold">所用软件：Mothur（v.1.34.0）</span></p>
<p><span class="bold">我们通过绘制shannon稀释曲线（shannon rarefaction curve）来评价测序量是否足够，并间接反映样品中物种的丰富程度。shannon指数作为一个评价样品内物种多样性程度的指标，值越高代表多样性程度越高。shannon稀释曲线是通过抽样n个tags来计算shannon指数的期望值，然后根据一组n值（一般为一组小于总序列数的等差数列）与其相对应的 shannon的期望值做出曲线来，当曲线趋于平缓或者达到平台期时也就可以认为测序深度增加已经不影响物种多样性，测序量趋于饱和。</span></p>
HTML
	
	my $shannon_img_desc = <<TEXT;
说明：横坐标表示抽取的 tags 数量；纵坐标表示抽取一定数量 tags 时所计算得到的shannon的期望值。 
TEXT
	
	my $rank_desc = <<HTML;
<p><span class="bold">我们将样品中的OTUs按相对丰度(或者包含的序列数目)由大到小排序得到对应的排序编号，再以OTUs的排序编号为横坐标，OTUs中的相对丰度（也可用该等级OTU中序列数的相对百分含量）为纵坐标,将这些点用折线连接，即绘制得到Rank Abundance曲线。</span></p>
<p><span class="bold">Rank Abundance曲线可直观的反应样品中包含的分类丰富度和均匀度，即在水平方向，分类的丰度由曲线的宽度来反映，分类的丰富度越高，曲线在横轴上的跨度越大；在垂直方向曲线的平滑程度，反映了样品中分类的均匀程度，曲线越平缓，物种分布越均匀。</span></p>
HTML
	
	my $rank_img_desc = <<TEXT;
说明：横坐标是OTU相对丰度从大到小的排序；纵坐标表示该OTU的相对表达丰度。 
TEXT
	
	my $otu_heatmap_desc = <<HTML;
<p><span class="bold">所用软件：R中的 <b>pheatmap</b> 包</span></p>
<p><span class="bold">我们根据OTU的表达谱数据，使用热图来展示不同的OTU在各样品间的表达变化情况，同时可以根据热图上的聚类关系，也可以反应样本关系。</span></p>
<p><span class="bold">因为OTU的数目较多，且多数OTU丰度都很低（包含tags数量为1），所以我们使用OTU至少在一个样本中包含tags数量达到总tags数量的0.1%作为阈值，对满足该条件的OTU进行热图分析</span></p>
<p><span class="bold">作图所用数据在 <a href="../2.otu/analysis/" target="_blank">2.otu/analysis</a> 目录下的 <a href="../2.otu/analysis/otu_exp.filter" target="_blank">otu_exp.filter</a> 文件中<br/></span></p>
HTML
	
	my $otu_pca_desc = <<HTML;
<p><span class="bold">所用软件：R中的<b>gmodels和scatterplot3d</b>包</span></p>
<p><span class="bold">我们根据OTU的表达谱数据，使用主成分分析来观察样本之间的关系</span></p>
<p><span class="bold">主成分分析(PCA)是通过降维寻找变量间的共线性关系，将一组可能相关的变量转换为一组不相关的变量，即主成分。各主成分间呈正交关系，主成分的数量小于等于变量的个数，其中第一主成分可以解释数据中最大的差异值，第二主成分则可以解释剩余差异中的最大差异，以此类推。</span></p>
<p><span class="bold">我们使用2D和3D两种形式，来展示主成分分析的结果，见下面的2张图</span></p>
<p><span class="bold">因为OTU的数目较多，且多数OTU丰度都很低（包含tags数量为1），所以我们使用OTU至少在一个样本中包含tags数量达到总tags数量的0.1%作为阈值，对满足该条件的OTU进行PCA分析</span></p>
<p><span class="bold">作图所用数据在 <a href="../2.otu/analysis/" target="_blank">2.otu/analysis</a> 目录下的 <a href="../2.otu/analysis/otu_exp.filter" target="_blank">otu_exp.filter</a> 文件中<br/></span></p>
HTML
	
	my $otu_beta_desc = <<HTML;
<p><span class="bold">基于之前生成的OTU的表达谱文件，我们可以分析各OTU在样品中的含量，进而计算出不同样品间在OTU水平上的 beta diversity。
本分析中通过计算 Whittaker's 来表征 beta 多样性<sup><a name="cite_back_7" href="#cite7">[7]</a></sup>，计算公式如下：</span></p>
<div style="margin:0 auto; width:605px;">
<table style="border:0px #000000 solid;">
<tr style="border:0px #000000 solid;"><td style="border:0px #000000 solid;">
<div class="tc"><a href="../src/image/beta_formula.jpg" target="_blank"><img style="width:200px" src="../src/image/beta_formula.jpg" /></a></div>
</td></tr>
</table>
</div>

<p><span class="bold">其中S表示2个样品中总的OTU数，a表示2个样品共有的otu的总数。</span></p>
<p><span class="bold">因为OTU的数目较多，且多数OTU丰度都很低（包含tags数量为1），所以我们使用OTU至少在一个样本中包含tags数量达到总tags数量的0.1%作为阈值，对满足该条件的OTU进行beta diversity分析</span></p>
<p><span class="bold">alpha多样性反映的是一个样品中的物种多样性程度，而beta多样性反映的则是不同样品间在物种多样性方面存在的差异大小，beta diversity 值越接近 0，表示这两个样品在物种多样性方面存在的差异越小。</span></p>
<p><span class="bold">作图所用数据在 <a href="../2.otu/analysis/" target="_blank">2.otu/analysis</a> 目录下的 <a href="../2.otu/analysis/otu_exp.filter.matrix" target="_blank">otu_exp.filter.matrix</a> 文件中<br/></span></p>
HTML
	
	my $otu_cluster_desc = <<HTML;
<p><span class="bold">所用软件：R中的<b>pvclust</b></span></p>
<p><span class="bold">根据OTU的表达谱，计算样品间距离，并对样品进行聚类分析，以判断在OTU水平上各样品的相似性。距离计算方法为 kld_jsd，
自展数（bootstrap值）为 100，结果如下图所示。聚类分析采用 R 软件提供的 pvclust 包进行<sup><a name="cite_back_8" href="#cite8">[8]</a></sup>，
并提供两类 p-value 评价聚类的准确性：AU  (Approximately  Unbiased)  p-value 和 BP  (Bootstrap  Probability)  p–value，其中 AU 是更接近无偏向性的评价指标。每个节点上红色和绿色分别表示使用两种检验方法 AU 和 BP 得到的支持此类聚类结果的 p-value，数值越大表示可靠性越高。</span></p>
<p><span class="bold">因为OTU的数目较多，且多数OTU丰度都很低（包含tags数量为1），所以我们使用OTU至少在一个样本中包含tags数量达到总tags数量的0.1%作为阈值，对满足该条件的OTU进行聚类分析</span></p>
<p><span class="bold">作图所用数据在 <a href="../2.otu/analysis/" target="_blank">2.otu/analysis</a> 目录下的 <a href="../2.otu/analysis/otu_exp.filter" target="_blank">otu_exp.filter</a> 文件中<br/></span></p>
HTML
	
	my $otu_bray_desc = <<HTML;
<p><span class="bold">所用软件：R</span></p>
<p><span class="bold">根据OTU的表达谱，计算样品间bray-curtis系数，并根据bray-curtis系数计算结果进行层级聚类，以判断在OTU水平上各样品的相似性。bray-curtis系数计算的数据基础是一个物种在该群落中是否存在，由于在群落中各个物种权重及丰度有比较大的差异，所以相较于其他量化群落差异的指标，bray-curtis系数更常被大部分文章所应用。</span></p>
<p><span class="bold">因为OTU的数目较多，且多数OTU丰度都很低（包含tags数量为1），所以我们使用OTU至少在一个样本中包含tags数量达到总tags数量的0.1%作为阈值，对满足该条件的OTU进行bray-curtis系数分析</span></p>
<p><span class="bold">作图所用数据在 <a href="../2.otu/analysis/" target="_blank">2.otu/analysis</a> 目录下的 <a href="../2.otu/analysis/otu_exp.filter" target="_blank">otu_exp.filter</a> 文件中<br/></span></p>
HTML
	
	$section->menu("高级信息分析(OTU)");
	$section->submenu("OTU 丰度分析");
	$section->desc($otu_desc);
	$section->tsv2html(-file=>"$outdir/2.otu/stat/stat_otu.xls",-name=>"各样品在 0.03 距离下 OTU 的数量",'-header'=>1,'-top'=>$num+1);
	$section->img2html(-file=>"../2.otu/stat/otuAbdDistr.png",-name=>"各样品OTUs的丰度分布",-desc=>$otu_abudance_fig_desc);
	
	$section->submenu("OTU 物种注释");
	$section->desc($otu_taxon_desc);
	
	# pathway annotation just for 16S sequencing, ITS can't do 
	if ($conf->{SequenceTitle} =~ /16S/i)
	{
		$section->submenu("OTU Pathway 注释");
		$section->desc($otu_pathway_desc);
		$section->desc($otu_pathway_tab_desc);
	
	
		# if sample numbers greater than 10, omits the samples after 9th sample (from the 11th column).
		my $omits = "";
		my $kegg_allow_num = 10;
		if ($num > $kegg_allow_num)
		{
			my $start = $kegg_allow_num + 1;
			my $end = $num + 1;
			$omits = "$start:$end";
		}
	
		$section->tsv2html(-file=>"$outdir/2.otu/annot/meta_ko_annot.xls",-name=>"OTU Pathway注释表（前20行）",-skip=>1,-max_chars=>20,-omits=>$omits,-top=>20);
		$section->imgs2html(-files=>\@pathway_stat_imgs,-names=>\@samples,-name=>"单样品OTU Pathway注释统计图",-note=>$pathway_stat_img_desc);
	}
	
	my $allow_expr_num = 3;
	my $omits = "";
	if ($num > $allow_expr_num)
	{
		my $start1 = $allow_expr_num + 1;
		my $end1 = $num + 1;
		my $start2 = 1 + $num + $allow_expr_num;
		my $end2 = 2*$num + 1;
		
		$omits = "$start1:$end1,$start2:$end2";
	}
	
	$section->submenu("OTU 表达谱");
	$section->desc($otu_expr_desc);
	$section->desc($otu_expr_tab_desc);
	#$section->tsv2html(-file=>"$outdir/2.otu/expression_profile/otu.profile.xls",-name=>"OTU表达谱(前20行)",-max_chars=>20,-top=>20,-omits=>$omits,-class=>"hl_table");
	$section->tsv2html(-file=>"$outdir/2.otu/expression_profile/otu.profile.xls",-name=>"OTU表达谱(前20行)",-max_chars=>20,-top=>20);
	
	$section->submenu("OTU 稀释曲线");
	$section->desc($otu_rarefaction_curve_desc);
	$section->img2html(-file=>"../2.otu/analysis/otu.rarefaction.png",-name=>"样品在 0.03 距离下的OTU稀释曲线图",-desc=>$otu_rarefaction_img_desc);
	
	$section->submenu("OTU alpha多样性分析");
	$section->add_html($otu_alpha_diversity_desc);
	$section->tsv2html(-file=>"$outdir/2.otu/analysis/alpha_diversity_short.xls",-name=>"样品在 0.03 距离下的 Alpha 丰富程度表",'-top'=>$num+1);
	
	$section->submenu("OTU shannon稀释曲线");
	$section->add_html($shannon_desc);
	$section->img2html(-file=>"../2.otu/analysis/shannon.rarefaction.png",-name=>"样品在 0.03 距离下的shannon稀释曲线图",-desc=>$shannon_img_desc);
	
	$section->submenu("OTU Rank Abundance曲线");
	$section->add_html($rank_desc);
	$section->img2html(-file=>"../2.otu/analysis/Rank_abd_Distr.png",-name=>"样品在 0.03 距离下Rank Abundance曲线图",-desc=>$rank_img_desc);
	
	# heatmap 
	if ($num >= 2)
	{
		my $heatmap_desc = "说明：横向表示OTU，纵向表示样品";
		
		$section->submenu("OTU 热图分析（样品数≥2）");
		$section->add_html($otu_heatmap_desc);
		$section->img2html(-file=>"../2.otu/analysis/otu_exp.filter.heatmap.png",-name=>"OTU表达谱热图",-desc=>$heatmap_desc);
	}
	
	if ($num >=3)
	{
		my $pca_desc1 = <<TEXT;
说明：PC1坐标表示第一主成分，括号中的百分比则表示第一主成分对样品差异的贡献值； PC2坐标表示第二主成分，
括号中的百分比表示第二主成分对样品差异的贡献值。图中有颜色的点分别表示各个样品。
TEXT
		
		my $pca_desc2 = <<TEXT;
说明： PC1坐标表示第一主成分，括号中的百分比则表示第一主成分对样品差异的贡献值；
PC2坐标表示第二主成分，括号中的百分比表示第二主成分对样品差异的贡献值；
PC3坐标表示第三主成分，括号中的百分比表示第三主成分对样品差异的贡献值。图中有颜色的点分别表示各个样品。
TEXT
		
		$section->submenu("OTU 主成分分析（样品数≥3）");
		$section->add_html($otu_pca_desc);
		$section->img2html2(-file1=>"../2.otu/analysis/otu_exp.filter.PCA2D.png",-file2=>"../2.otu/analysis/otu_exp.filter.PCA3D.png",
		                    -name1=>" 样品的PCA图（2D）",-name2=>" 样品的PCA图（3D）",-desc1=>$pca_desc1,-desc2=>$pca_desc2);
		$section->img2html2(-file1=>"../2.otu/analysis/otu_exp.filter.PCA2D.nonames.png",-file2=>"../2.otu/analysis/otu_exp.filter.PCA3D.nonames.png",
		                    -name1=>" 样品的PCA图（2D，不显示样品名）",-name2=>" 样品的PCA图（3D，不显示样品名）",-desc1=>$pca_desc1,-desc2=>$pca_desc2);
	}
	
	
	if ($num>=2)
	{
		$section->submenu("OTU beta多样性分析（样品数≥2）");
		$section->add_html($otu_beta_desc);
		#$section->tsv2html(-file=>"$outdir/2.otu/analysis/otu_exp.filter.matrix",-name=>"两两样本间的beta多样性表",-top=>$num+1);
		$section->img2html(-file=>"../2.otu/analysis/otu_exp.filter.betadiversity.png",-name=>"样品的OTU水平的beta diversity热图");
	}
		
	if ($num >=3)
	{
		$section->submenu("OTU 聚类分析（样品数≥3）");
		$section->add_html($otu_cluster_desc);
		$section->img2html(-file=>"../2.otu/analysis/otu_exp.filter.kld_jsd.png",-name=>"样品的聚类分析图");
	}
		
	if ($num >=2)
	{
		$section->submenu("OTU bray-curtis系数分析（样品数≥2）");
		$section->add_html($otu_bray_desc);
		$section->img2html(-file=>"../2.otu/analysis/otu_exp.filter.colm.bray.png",-name=>"样品的bray-curtis系数聚类图");
	}
}

sub senior_taxon
{
	my $section = shift;
	
	my @taxon_levels = ("Domain","Phylum","Class","Order","Family","Genus","Species");
	my @taxon_levels_chinese = ("界","门","纲","目","科","属","种");
	my $num = scalar @samples;
	my $tmp = 8 + $num;
	my $tmp1 = $tmp + 1;
	my $tmp2 = $tmp + $num;
	
	my $taxon_expr_desc = <<HTML;
<p><span class="bold">结合OTU的物种注释信息以及OTU在不同样品中的表达，我们按照 界->门->纲->目->科->属->种 统计了每一个分类水平上各样品的表达情况。 </span></p>
<p><span class="bold">将不同样品中属于同一物种的 Tag 数量汇总在同一个表格中，生成物种 profiling 表，如下表所示。
表中第1列是分类等级，0 表示界（Domain），1 表示门（Phylum），2 表示纲（Class），以此类推；第2至第8列是不同分类等级所对应的物种分类信息；
第9至第$tmp列表示各个样品所含的Tag序列数（物种绝对丰度）；第$tmp1列至$tmp2列是各个样品所含的Tag序列数占总Tag数的百分比（物种相对丰度）。
从这个 profiling 表中可以很容易的比较同一物种在不同样品中的丰度差异，从而找出不同样品中差异显著的物种。</span></p>
<p>结果文件在文件夹<a href="../3.taxa/expression_profile/" target="_blank">3.taxa/expression_profile</a>下：</p>
HTML
	
	my $taxon_tree_desc = <<HTML;
<p>所用软件：perl + SVG</p>
<p><span>根据物种的分类表达谱的数据，选取丰度较高的部分物种分类单元，我们做出了物种分类树的展示图。</span></p>
HTML
	
	my $taxon_tree_fig_desc = <<HTML;
说明：各个饼图中不同的颜色的区域代表不同的样品在该分类单元上的比率，半径的大小代表该分类单元所包含的tag数占总tag的比例，
半径越大代表丰度越高，饼图旁边的百分比代表该分类单元的tag数占总tag数的百分比。
HTML
	
	my ($best_level,$best_level_ratio,$best_level_next,$best_level_next_ratio,$best_level_pre) = &fetch_best_taxon_level("$outdir/3.taxa/stat");
	
	my $best_taxon_level_normal = <<HTML;
<p><span class="bold">为了确定最佳的物种分类水平，我们统计了在各个分类水平上的 tag 序列数。在进行分类分析时，
我们总是希望所得到的序列能够尽可能地注释到更低的分类等级上，但事实是，随着注释等级的降低（如从属到种），能够注释到下一等级的序列条数总是呈下降趋势。
所谓最佳分类水平，即是指分类等级尽可能低，注释上的 Tag 数量尽可能多的水平。</span></p>
<p><span class="bold">如 下图 所示，$num 个样品均有多于 $best_level_ratio 的 Tag 序列能够注释到“$best_level”的水平，而能够注释到“$best_level_next”的水平的 tag 序列低于 $best_level_next_ratio，
这种情况下我们选择“$best_level”作为 $num 个样品的最佳分类水平，因为在该水平上物种的等级与注释到的 Tag 数量这两个因素达到了平衡，如果选择更低的“$best_level_next”的等级，
则用于后续分析的 Tag 数量将大大减少，而如果选择“$best_level_pre”的分类等级，则违背了尽可能注释到更低等级的分类原则。</span></p>
<p>统计结果见在文件夹：<a href="../3.taxa/stat" target="_blank">3.taxa/stat</a>下：</p>
HTML
	
	my $best_taxon_level_domain = <<HTML;
<p><span class="bold">为了确定最佳的物种分类水平，我们统计了在各个分类水平上的 tag 序列数。在进行分类分析时，
我们总是希望所得到的序列能够尽可能地注释到更低的分类等级上，但事实是，随着注释等级的降低（如从属到种），能够注释到下一等级的序列条数总是呈下降趋势。
所谓最佳分类水平，即是指分类等级尽可能低，注释上的 Tag 数量尽可能多的水平。</span></p>
<p><span class="bold">如 下图 所示，$num 个样品均有多于 $best_level_ratio 的 Tag 序列能够注释到“$best_level”的水平，而能够注释到“$best_level_next”的水平的 tag 序列远低于 $best_level_next_ratio，
这种情况下我们只能选择“$best_level”作为 $num 个样品的最佳分类水。</span></p>
<p>统计结果见在文件夹：<a href="../3.taxa/stat" target="_blank">3.taxa/stat</a>下：</p>
HTML

	my $best_taxon_level = $best_level_pre ? $best_taxon_level_normal : $best_taxon_level_domain;
	
	my $taxon_fill_bar = <<HTML;
<p><span class="bold">我们统计了各个层级分类水平上的各样品的物种组成情况，然后用堆叠图的形式，直观展示不同的样品在各个分类层级水平上的物种丰度的变化情况。</span></p>
<p><span class="bold">为了画图的美观，我们只展示至少在一个样本中的表达丰度达到 2%的物种，其余物种统一归类到Other类别中去，无法注释到该水平的tags则被归类到Unclassified类别中去。</span></p>
<p><span class="bold">作图数据在目录<a href="../3.taxa/expression_profile" target="_blank">3.taxa/expression_profile</a>下：</span></p>
HTML
	
	my $phy_tree_desc = <<HTML;
<p><span class="bold">在某个分类水平上，以最佳分类水平"$best_level"为例，我们将每个$best_level中丰度最高的OTU的序列来作为其代表序列，
将丰度达到一定阈值的$best_level进行了物种系统发生进化树分析。并将属于同一门的物种标以相同颜色，不同样本中同一$best_level的丰度则以堆叠图的方式在外围进行展示，
进化树堆叠图能够直观展示不同样品间的优势菌群的结构组成差异。</span></p>
<p><span class="bold">作图数据在目录<a href="../3.taxa/expression_profile/tree_stack/" target="_blank">3.taxa/expression_profile/tree_stack</a>下：</span></p>
HTML
	
	my @files = ("profiling_all.xls","profiling_Domain.xls","profiling_Phylum.xls","profiling_Class.xls","profiling_Order.xls","profiling_Family.xls","profiling_Genus.xls","profiling_Species.xls");
	my @profiling_files = map { "../3.taxa/expression_profile/$_" } @files;
	my @profiling_files_desc = ("所有分类水平上的各样品表达谱总表","界水平上的各样品表达谱总表","门水平上的各样品表达谱总表","纲水平上的各样品表达谱总表",
		"目水平上的各样品表达谱总表","科水平上的各样品表达谱总表","属水平上的各样品表达谱总表","种水平上的各样品表达谱总表");
	
	$section->menu("高级信息分析(物种分类)");
	
	$section->submenu("物种分类表达谱");
	$section->add_html($taxon_expr_desc);
	$section->files2list(-files=>\@profiling_files,-desc=>\@profiling_files_desc);
	
	my $allow_expr_num = 3;
	my $omits = "";
	if ($num > $allow_expr_num)
	{
		my $start1 = $allow_expr_num + 8;
		my $end1 = $num + 8;
		my $start2 = 8 + $num + $allow_expr_num;
		my $end2 = 2*$num + 8;
		
		$omits = "$start1:$end1,$start2:$end2";
	}
	
	$section->tsv2html(-file=>"$outdir/3.taxa/expression_profile/profiling_Order.xls",
		-name=>"目水平上的各样品表达谱总表（前20行）",'-top'=>20,-omits=>$omits);
	
	$section->submenu("物种分类树");
	$section->add_html($taxon_tree_desc);
	$section->img2html(-file=>"../3.taxa/expression_profile/taxtree.png",-name=>"样品的物种分类树",-desc=>$taxon_tree_fig_desc);
	
	my @stat_files = map { "../3.taxa/stat/$_" } ("wholeTaxStat","best_level_stat.xls","best_level");
	my @stat_files_desc = ("样品各分类水平中 Tags 数统计表(下图的绘图数据)","样品 Tags 各分类水平注释率","样品 Tags 的最佳分类水平注释率");
	
	$section->submenu("最佳物种分类水平");
	$section->add_html($best_taxon_level);
	$section->files2list(-files=>\@stat_files,-desc=>\@stat_files_desc);
	$section->img2html2(-file1=>"../3.taxa/stat/wholeTaxStat.TagRatio.png",-file2=>"../3.taxa/stat/wholeTaxStat.TagNumber.png",
		-name1=>"样品各分类水平中 Tags 比例统计",-name2=>"样品各分类水平中 Tags 数量统计",
		-desc1=>"说明：横坐标是样品 ID，纵坐标是在各分类等级上所能鉴定的 tags 占总Tags的比例。",-desc2=>"说明：横坐标是样品 ID，纵坐标是在各分类等级上所能鉴定的 tags 数。");
	
	my @taxon_fill_bar_data = map { "../3.taxa/expression_profile/$taxon_levels[$_]_StackMap" } 1 .. $#taxon_levels;
	my @taxon_fill_bar_data_desc = map { "$taxon_levels_chinese[$_]分类水平的作图数据" } 1 .. $#taxon_levels_chinese;
	my @taxon_fill_bar_imgs = map { "../3.taxa/expression_profile/$taxon_levels[$_]_StackMap.png" } 1 .. $#taxon_levels;
	my @taxon_levels_chinese_noDomain = @taxon_levels_chinese[1 .. $#taxon_levels_chinese];
	
	$section->submenu("界以下分类水平上的物种分布堆叠图分析");
	$section->add_html($taxon_fill_bar);
	$section->files2list(-files=>\@taxon_fill_bar_data,-desc=>\@taxon_fill_bar_data_desc);
	$section->imgs2html(-files=>\@taxon_fill_bar_imgs,-names=>\@taxon_levels_chinese_noDomain,-name=>"界以下分类水平上的物种分布堆叠图");
	
	my @phy_tree_imgs = map { "../3.taxa/expression_profile/tree_stack/" . $taxon_levels[$_] . "_legend.png" } 2 .. $#taxon_levels;
	my @phy_tree_names = map { $taxon_levels_chinese[$_] } 2 .. $#taxon_levels;
	$section->submenu("门以下分类水平上的物种系统发生进化树",-help=>"meta16S_help.html#系统发生进化树");
	$section->add_html($phy_tree_desc);
	#$section->files2list();
	$section->imgs2html(-files=>\@phy_tree_imgs,-names=>\@phy_tree_names,-name=>"门以下分类水平上的物种系统发生进化树");
	
	if ($num>=2)
	{
		my $taxon_heatmap_desc = <<HTML;
<p>所用软件：<b>R</b>语言的<b>pheatmap</b>包</p>
<p>我们根据物种分类的表达谱数据，使用热图来展示不同的物种在各样品间的表达情况，同时根据热图上的聚类关系，也可以反应样本关系。</p>
<p>为了降低噪音，我们使用物种至少在一个样品中包含tags数量达到总tags数量的0.1%作为阈值，对于满足该条件的物种进行热图分析。</p>
<p>作图所用数据在目录<a href="../3.taxa/analysis" target="_blank">3.taxa/analysis</a>下各个分类的目录下的<b>*_exp.filter</b>文件中。</p>
HTML
		
		my @heatmap_names = map { $taxon_levels_chinese[$_] } 1 .. $#taxon_levels;
		my @heatmap_imgs = map { my $flag = $_ + 1; "../3.taxa/analysis/$flag.$taxon_levels[$_]/$taxon_levels[$_]_exp.filter.heatmap.png" } 1 .. $#taxon_levels;
		
		$section->submenu("界以下分类水平上的物种分类热图分析（样品数≥2）");
		$section->add_html($taxon_heatmap_desc);
		$section->imgs2html(-files=>\@heatmap_imgs,-names=>\@heatmap_names,-name=>"界以下分类水平上的物种分类热图");
	}
	
	if ($num >= 3)
	{
		my $taxon_pca_desc = <<HTML;
<p>所用软件：<b>R</b>语言的<b>gmodels</b>包</p>
<p>我们根据物种分类的表达谱数据，使用主成分分析来观察样品之间的关系。</p>
<p>主成分分析(PCA)是通过降维寻找变量间的共线性关系，将一组可能相关的变量转换为一组不相关的变量，即主成分。各主成分间呈正交关系，
主成分的数量小于等于变量的个数，其中第一主成分可以解释数据中最大的差异值，第二主成分则可以解释剩余差异中的最大差异，以此类推。
我们使用2D和3D两种形式，来展示PCA的结果，见下图。</p>
<p>为了降低数据噪音，所以我们使用物种至少在一个样本中包含tags数量达到总tags数量的0.1%作为阈值，对满足该条件的物种进行PCA分析。</p>
<p>作图所用数据在目录<a href="../3.taxa/analysis" target="_blank">3.taxa/analysis</a>下各个分类的目录下的<b>*_exp.filter</b>文件中。</p>
HTML
		my @pca_names = map { $taxon_levels_chinese[$_] } 1 .. $#taxon_levels;
		my @pca_2d_imgs = map { my $flag = $_ + 1; "../3.taxa/analysis/$flag.$taxon_levels[$_]/$taxon_levels[$_]_exp.filter.PCA2D.png" } 1 .. $#taxon_levels;
		my @pca_3d_imgs = map { my $flag = $_ + 1; "../3.taxa/analysis/$flag.$taxon_levels[$_]/$taxon_levels[$_]_exp.filter.PCA3D.png" } 1 .. $#taxon_levels;
		my @pca_2d_noname_imgs = map { my $flag = $_ + 1; "../3.taxa/analysis/$flag.$taxon_levels[$_]/$taxon_levels[$_]_exp.filter.PCA2D.nonames.png" } 1 .. $#taxon_levels;
		my @pca_3d_noname_imgs = map { my $flag = $_ + 1; "../3.taxa/analysis/$flag.$taxon_levels[$_]/$taxon_levels[$_]_exp.filter.PCA3D.nonames.png" } 1 .. $#taxon_levels;
		
		
		$section->submenu("界以下分类水平上的主成分分析（样品数≥3）");
		$section->add_html($taxon_pca_desc);
		$section->imgs2html2(-files1=>\@pca_2d_imgs,-files2=>\@pca_3d_imgs,-names=>\@pca_names,-name=>"界以下分类水平上的PCA图");
		$section->imgs2html2(-files1=>\@pca_2d_noname_imgs,-files2=>\@pca_3d_noname_imgs,-names=>\@pca_names,-name=>"界以下分类水平上的PCA图（不显示样品名）");
	}
	
	if ($num >= 2)
	{
		my $taxon_betadiversity_desc = <<HTML;
<p><span class="bold">基于物种分类表达谱数据，我们可以分析各类群在样品中的含量，进而计算出不同样品间在某个分类水平上的 beta  diversity。
本分析中通过计算 Whittaker's 来表征 beta 多样性，计算公式如下：</span></p>		
<div style="margin:0 auto; width:605px;">
<table style="border:0px #000000 solid;">
<tr style="border:0px #000000 solid;"><td style="border:0px #000000 solid;">
<div class="tc"><a href="../src/image/beta_formula.jpg" target="_blank"><img style="width:200px" src="../src/image/beta_formula.jpg" /></a></div>
</td></tr>
</table>
</div>

<p><span class="bold">其中S表示2个样品中总的物种数量，a表示2个样品共有的物种数量。</span></p>
<p><span class="bold">为了降低数据噪音，所以我们使用物种至少在一个样本中包含tags数量达到总tags数量的0.1%作为阈值，对满足该条件的物种进行beta diversity分析</span></p>
<p><span class="bold">beta多样性反映的是不同样品间在物种多样性方面存在的差异大小，beta diversity 值越接近 0，表示这两个样品在物种多样性方面存在的差异越小。</span></p>
<p>结果文件存放在目录<a href="../3.taxa/analysis/">3.taxa/analysis</a>下：</p>
HTML
		
		my @beta_names = map { $taxon_levels_chinese[$_] } 1 .. $#taxon_levels;
		my @matrix_files = map { my $flag = $_ + 1; "../3.taxa/analysis/$flag.$taxon_levels[$_]/$taxon_levels[$_]_exp.filter.matrix" } 1 .. $#taxon_levels;
		my @matrix_files_desc = map { "${_}分类水平上的两两样品间的beta diversity矩阵表" } @beta_names;
		my @taxon_beta_imgs = map { my $flag = $_ + 1; "../3.taxa/analysis/$flag.$taxon_levels[$_]/$taxon_levels[$_]_exp.filter.betadiversity.png" } 1 .. $#taxon_levels;
		
		$section->submenu("界以下分类水平上的beta多样性分析（样品数≥2）");
		$section->add_html($taxon_betadiversity_desc);
		$section->files2list(-files=>\@matrix_files,-desc=>\@matrix_files_desc);
		$section->imgs2html(-files=>\@taxon_beta_imgs,-names=>\@beta_names,-name=>"界以下分类水平上的beta diversity图");
	}
	
	if ($num >= 3)
	{
		my $taxon_cluster_desc = <<HTML;
<p>根据在各个分类水平上各样品的表达谱数据，计算样品间距离，并对样品进行聚类分析，以判断在某个分类水平上各样品的相似性。距离计算方法为 kld_jsd，自展数（bootstrap值）为 100，结果如下图所示。</p>
<p>聚类分析采用 R 软件提供的 pvclust 包进行，并提供两类 p-value 评价聚类的准确性：AU  (Approximately  Unbiased)  p-value 和 BP  (Bootstrap  Probability)  p–value，其中 AU 是更接近无偏向性的评价指标。每个节点上红色和绿色分别表示使用两种检验方法 AU 和 BP 得到的支持此类聚类结果的 p-value，数值越大表示可靠性越高。</p>
<p>为了降低数据噪音，所以我们使用物种至少在一个样本中包含tags数量达到总tags数量的0.1%作为阈值，对满足该条件的物种进行聚类分析。</p>
<p>作图所用数据在目录<a href="../3.taxa/analysis" target="_blank">3.taxa/analysis</a>下各个分类的目录下的<b>*_exp.filter</b>文件中。</p>
HTML
		
		my @cluster_names = map { $taxon_levels_chinese[$_] } 1 .. $#taxon_levels;
		my @cluster_imgs = map { my $flag = $_ + 1; "../3.taxa/analysis/$flag.$taxon_levels[$_]/$taxon_levels[$_]_exp.filter.kld_jsd.png" } 1 .. $#taxon_levels;
		
		$section->submenu("界以下分类水平上的聚类分析（样品数≥3）");
		$section->add_html($taxon_cluster_desc);
		$section->imgs2html(-files=>\@cluster_imgs,-names=>\@cluster_names,-name=>"界以下分类水平上的样品聚类分析图");
	}
	
	if ($num >= 2)
	{
		my $taxon_bray_desc = <<HTML;
<p>根据在各个分类水平上各样品的表达谱数据，计算样品间bray-curtis系数，并根据bray-curtis系数的计算结果对样品进行层级聚类，以判断在某个分类水平上各样品的相似性。同时我们将某个分类水平上的物种组成堆叠图与bray-curtis系数的聚类结果结合在一起进行展示。
<p>为了降低数据噪音，所以我们使用物种至少在一个样本中包含tags数量达到总tags数量的0.1%作为阈值，对满足该条件的物种进行聚类分析。</p>
<p>作图所用数据在目录<a href="../3.taxa/analysis" target="_blank">3.taxa/analysis</a>下各个分类的目录下的<b>*_exp.filter</b>文件中。</p>
HTML
		
		my @bray_names = map { $taxon_levels_chinese[$_] } 1 .. $#taxon_levels;
		my @bray_imgs = map { my $flag = $_ + 1; "../3.taxa/analysis/$flag.$taxon_levels[$_]/$taxon_levels[$_].bray_stack.png" }  1 .. $#taxon_levels; 
		$section->submenu("界以下分类水平上的bray-curtis系数分析（样品数≥2）");
		$section->add_html($taxon_bray_desc);
		$section->imgs2html(-files=>\@bray_imgs,-names=>\@bray_names,-name=>"界以下分类水平上的bray-curtis系数聚类分析及物种组成堆叠图");
	}
}

sub different_analysis
{
	my @taxon_levels = ("Domain","Phylum","Class","Order","Family","Genus","Species");
	my @taxon_levels_chinese = ("界","门","纲","目","科","属","种");
	my $num = scalar @samples;
	
	$section->menu("组间差异分析");
	
	if ($conf->{Group_diff_metastat})
	{
		my $taxon_diff_desc = <<HTML;
<p>所用软件：Metastats</p>
<p>通过统计学的方法(Metastats使用的是fisher精确检验)检验两组样品间微生物群落丰度的差异，并使用FDR评估差异的显著性。找出导致两组样品组成差异的物种。</p>
<p>结果文件保存在目录<a href="../4.Group_diff/metastat" target="_blank"></a>下，
其中第一列表示的最佳分类的水平，为了避免数据量带来的误差，mean(平均值)、variance(方差)、std.err(标准误差)均使用百分比(即该物种tag数除以总tag数)来计算，最后三列分别是差异的P-value及FDR(矫正后的P-value)，log2FC(平均物种丰度的差异倍数取log2的值)。</p>
HTML
		
		$section->submenu("各分类水平上的样品组间差异分析");
		$section->add_html($taxon_diff_desc);
		
		# print the result file list 
		my @groups = split /,/,$conf->{Group_diff_metastat};
		
		foreach my $group (@groups)
		{
			$group =~ s/&/-VS-/;
			my @result_files;
			my @result_files_desc;
			
			foreach (0 .. $#taxon_levels)
			{
				my$flag = $_+1;
				if (-e "$outdir/4.Group_diff/metastat/$flag.$taxon_levels[$_]/$group.metastat.result.xls")
				{
					push @result_files , "../4.Group_diff/metastat/$flag.$taxon_levels[$_]/$group.metastat.result.xls";
					push @result_files_desc , "$taxon_levels_chinese[$_]分类水平上的差异分析结果";
				}
			}
			
			#my @result_files = map { my$flag = $_+1; "../4.Group_diff/metastat/$flag.$taxon_levels[$_]/$group.metastat.result.xls" } 0 .. $#taxon_levels;
			#my @result_files_desc = map { "${_}分类水平上的差异分析结果" } @taxon_levels_chinese;
			
			$section->desc("<b>$group</b>在各分类水平上的差异分析结果：");
			$section->files2list(-files=>\@result_files,-desc=>\@result_files_desc);
		}
		
		# add the demo table 
		my $order = ${best_taxon} + 1;
		my $best_level = $taxon_levels_chinese[$best_taxon];
		my $best_level_en = $taxon_levels[$best_taxon];
		my $frt_group = $groups[0];
		my $result = "$outdir/4.Group_diff/metastat/$order.$best_level_en/$frt_group.metastat.result.xls";
		
		if ( -e $result)
		{
			my $name = "<b>$frt_group</b>在最佳分类水平<b>${best_level}</b>下的组间差异分析";
			$section->desc("下表是<b>$frt_group</b>在最佳分类水平 <b>${best_level}</b> 下的差异分析结果：");
			$section->tsv2html(-file=>$result,-name=>$name,-top=>20);
		}
		else 
		{
			$result = "$outdir/4.Group_diff/metastat/3.Class/$frt_group.metastat.result.xls";
			my $name = "<b>$frt_group</b>在纲分类水平下的差异分析结果";
			$section->desc("下表是<b>$frt_group</b>在门分类水平下的差异分析结果：");
			$section->tsv2html(-file=>$result,-name=>$name,-top=>20);
		}
		
		# pathway 富集分析 , just for 16S
		if ($conf->{"SequenceTitle"} =~ /16S/i)
		{
			my $pathway_enrich_desc = <<HTML;
通过metastat分析以后，筛选出|Log2(FC)|>=1 以及Pvalue<=0.05 显著差异物种，并对其进行富集分析。
HTML
		
			my $pathway_enrich_bubble_desc = <<HTML;
根据富集分析的结果，我们根据qvalue值，选取显著性最高的前20个通路绘制KEGG pathway气泡图，如下所示：
HTML
	
			$section->submenu("各分类水平上的组间差异Pathway功能分析");
			$section->desc($pathway_enrich_desc,-help=>"meta16S_help.html#富集分析");
			$section->add_html($pathway_enrich_bubble_desc);
		
			foreach my $group (@groups)
			{
				my @pathway_enrich_bubble_imgs;
				my @pathway_enrich_bubble_names;

				foreach (0 .. $#taxon_levels) 
				{
					my $flag = $_ + 1;
					my $file = "$outdir/4.Group_diff/metastat/$flag.$taxon_levels[$_]/$group/$group.path.png";
					if (-e $file)
					{ 
						push @pathway_enrich_bubble_imgs , "../4.Group_diff/metastat/$flag.$taxon_levels[$_]/$group/$group.path.png";
						push @pathway_enrich_bubble_names , $taxon_levels_chinese[$_];
					}
				}
			
				next if ($#pathway_enrich_bubble_imgs == -1);
			
				my $name = "<font color=\"red\">$group</font>在各个分类水平上的Pathway富集分析气泡图";
				my $note = <<TEXT;
说明：图中x轴为RichFactor，等于差异的物种分类对应的K号/全部的物种分类对应的K；y轴为代谢图路；
点的大小表示注释上该通路中的全部物种分类数；点的颜色表示Qvalue的大小。
TEXT
				$section->imgs2html(-files=>\@pathway_enrich_bubble_imgs,-names=>\@pathway_enrich_bubble_names,-name=>$name,-note=>$note);
				$section->add_html("<br /><br />");
			}
		}
	}
	
	if ($conf->{Group_diff_Lefse})
	{
		my $lefse_desc = <<HTML;
<p>所用软件：LEFse。</p>
<p>通过LEFse分析组间菌群差异，可以找出各组间特异的主要菌群，有助于开发biomaker等研究。</p>
<p>利用LEFse软件对差异组间进行分析，LEFse先对所有组样品间进行kruskal-Wallis秩和检验（一种多样本比较时常用的检验方法），
将筛选出的差异再通过wilcoxon秩和检验（一种两样本成组比较常用的检验方法）进行两两组间比较，最后筛选出的差异使用LDA（Linear Discriminant Analysis）
得出的结果进行排序得到左图，左图展示了不同组中丰度差异显著的物种，柱状图的长度代表差异物种的影响大小（即为LDA Score）。
随后通过将差异映射到已知层级结构的分类树上方式得到进化分支图(右图)。在进化分支图中，由内至外辐射的圆圈代表了由门至属（或种）的分类级别。
在不同分类级别上的每一个小圆圈代表该水平下的一个分类，小圆圈直径大小与相对丰度大小呈正比。着色原则：无显著差异的物种统一着色为黄色。详细见下图：</p>
HTML
		$section->submenu("样品组间差异LEFse分析");
		$section->add_html($lefse_desc);
		
		$conf->{Group_diff_Lefse} =~ s/&/-vs-/g;
		my @groups = split /,/ , $conf->{Group_diff_Lefse};
		my @imgs1 = map { "../4.Group_diff/LefSe/${_}.Lefse.png" } @groups;
		my @imgs2 = map { "../4.Group_diff/LefSe/${_}.Lefse.cladogram.png" } @groups;
		
		$section->imgs2html2(-files1=>\@imgs1,-files2=>\@imgs2,-names=>\@groups,-name=>"LEFse差异分析图");
		
		$section->desc("LEFse还提供单个差异物种在各个比较组的真实表达量图，见下图：");
		foreach my$group (@groups)
		{
			my @single_taxon_imgs;
			my @names;
			
			my @tmp_files = glob("$outdir/4.Group_diff/LefSe/$group/*.png");
			
			foreach (@tmp_files)
			{
				my$fname = basename($_); 
				push @single_taxon_imgs , "../4.Group_diff/LefSe/$group/$fname";
				
				$fname =~ s/\.png//;
				push @names , $fname;
			}
			
			my $name = "单个物种在比较组 <font color=\"red\">$group</font> 中的真实表达量图(部分)";
			
			@single_taxon_imgs = @single_taxon_imgs[0 .. 9] if($#single_taxon_imgs > 9);
			@names = @names[0 .. 9] if ($#names > 9);
			$section->imgs2html(-files=>\@single_taxon_imgs,-names=>\@names,-name=>$name);
		}
	}
}

sub data_save
{
	my $section = shift;
	
	my $file_tree = <<HTML;
<div><pre>
result_root_dir
├── 1.tag                                 [tags结果]
│   ├── fasta                                 [各样品的tags序列]
│   │   └── *.fasta                               [各样品的tags序列文件(fasta格式)]
│   └── stat                                  [各样品tags序列统计结果]
│       ├── stat_tag.xls                          [各样品tags序列统计]
│       ├── stat_uniqTag.xls                      [各样品unique tags序列统计]
│       ├── tagAbdDistr                           [各样品的tag序列的丰度分布]
│       ├── tagAbdDistr.pdf                       [各样品的tag序列的丰度分布统计图(pdf格式)]
│       ├── tagAbdDistr.png                       [各样品的tag序列的丰度分布统计图(png格式)]
│       ├── tagLenDistr                           [各样品的tag序列的长度分布统计]
│       ├── tagLenDistr.pdf                       [各样品的tag序列的长度分布统计图(pdf格式)]
│       └── tagLenDistr.png                       [各样品的tag序列的长度分布统计图(png格式)]
├── 2.otu                                 [otu结果]
│   ├── analysis                              [otu高级分析结果]
│   │   ├── otu.rarefaction                       [OTU的稀释曲线数据]
│   │   ├── otu.rarefaction.pdf                   [OTU的稀释曲线的分布图（pdf格式）]
│   │   ├── otu.rarefaction.png                   [OTU的稀释曲线的分布图（png格式）]
│   │   ├── shannon.rarefaction                   [shannon稀释曲线数据]
│   │   ├── shannon.rarefaction.pdf               [shannon稀释曲线的分布图（pdf格式）]
│   │   ├── shannon.rarefaction.png               [shannon稀释曲线的分布图（png格式）]
│   │   ├── alpha_diversity_total.xls             [alpha多样性的统计总表]
│   │   ├── alpha_diversity_short.xls             [alpha多样性的统计简表]
│   │   ├── otu_exp.filter                        [过滤掉表达量小于0.1%的OTU后，剩下的OTU表达谱，是后续作图分析的输入数据]
│   │   ├── otu_exp.filter.matrix                 [beta多样性的矩阵]
│   │   ├── otu_exp.filter.betadiversity.pdf      [beta多样性图（pdf格式）]
│   │   ├── otu_exp.filter.betadiversity.png      [beta多样性图（png格式）]
│   │   ├── otu_exp.filter.heatmap.pdf            [otu表达谱热图（pdf格式）]
│   │   ├── otu_exp.filter.heatmap.png            [otu表达谱热图（png格式）]
│   │   ├── otu_exp.filter.colm.bray.pdf          [bray-curtis系数聚类图（pdf格式）]
│   │   ├── otu_exp.filter.colm.bray.png          [bray-curtis系数聚类图（png格式）]
│   │   ├── otu_exp.filter.PCA2D.pdf              [PCA图（2D）（pdf格式）]
│   │   ├── otu_exp.filter.PCA2D.png              [PCA图（2D）（png格式）]
│   │   ├── otu_exp.filter.PCA3D.pdf              [PCA图（3D）（pdf格式）]
│   │   ├── otu_exp.filter.PCA3D.png              [PCA图（3D）（png格式）]
│   │   ├── otu_exp.filter.PCA2D.nonames.pdf      [PCA图（2D）（pdf格式）（无样品名）]
│   │   ├── otu_exp.filter.PCA2D.nonames.png      [PCA图（2D）（png格式）（无样品名）]
│   │   ├── otu_exp.filter.PCA3D.nonames.pdf      [PCA图（3D）（pdf格式）（无样品名）]
│   │   ├── otu_exp.filter.PCA3D.nonames.png      [PCA图（3D）（png格式）（无样品名）]
│   │   ├── otu_exp.filter.PCA.samples.xls        [PCA分析中每个样品的坐标]
│   │   ├── otu_exp.filter.PCA.component.xls      [PCA分析中每个OTU的坐标]
│   │   ├── otu_exp.filter.kld_jsd.newick         [cluser图中的样品关系树文件]
│   │   ├── otu_exp.filter.kld_jsd.pdf            [cluster图（pdf格式）]
│   │   └── otu_exp.filter.kld_jsd.png            [cluster图（pdf格式）]
│   ├── annot                                 [otu pathway注释（仅16S的项目进行此项分析，ITS的没有）]
│   │   ├── meta_ko_annot.xls                     [otu pathway注释总表]
│   │   └── Sample                                [各样品otu pathway注释结果]
│   │       ├── *.path.xls                            [各样品的OTU Pathway注释结果统计表]
│   │       ├── *.png                                 [各样品的OTU Pathway注释结果统计图（png格式）]
│   │       └── *.svg                                 [各样品的OTU Pathway注释结果统计图（svg格式）]
│   ├── expression_profile                    [表达谱结果]
│   │   ├── otu.profile.xls                       [OTU的表达谱]
│   │   └── otu.representative.fasta              [每个OTU的代表性序列]
│   └── stat                                  [otu统计结果]
│       ├── stat_otu.xls                          [各样品otu数量统计]
│       ├── otuAbdDistr                           [各样品的otu的丰度分布]
│       ├── otuAbdDistr.pdf                       [各样品的otu的丰度分布统计图（pdf格式）]
│       └── otuAbdDistr.png                       [各样品的otu的丰度分布统计图（png格式）]
├── 3.taxa                                [物种分类结果]
│   ├── stat                                  [物种分类结果统计]
│   │   ├── wholeTaxStat                          [各分类水平上tags数量统计]
│   │   ├── wholeTaxStat.TagNumber.pdf            [各分类水平上tags数量统计图（pdf格式）]
│   │   ├── wholeTaxStat.TagNumber.png            [各分类水平上tags数量统计图（png格式）]
│   │   ├── wholeTaxStat.TagRatio.pdf             [各分类水平上tags比例统计图（pdf格式）]
│   │   ├── wholeTaxStat.TagRatio.png             [各分类水平上tags比例统计图（png格式）]
│   │   ├── best_level                            [最佳分类水平]
│   │   └── best_level_stat.xls                   [不同分类水平上的比例统计]
│   ├── expression_profile                    [物种分类表达谱结果]
│   │   ├── profiling_all.xls                     [所有分类水平上的各样品表达谱总表]
│   │   ├── profiling_Domain.xls                  [界水平上的各样品表达谱总表]
│   │   ├── profiling_Phylum.xls                  [门水平上的各样品表达谱总表]
│   │   ├── profiling_Class.xls                   [纲水平上的各样品表达谱总表]
│   │   ├── profiling_Order.xls                   [目水平上的各样品表达谱总表]
│   │   ├── profiling_Family.xls                  [科水平上的各样品表达谱总表]
│   │   ├── profiling_Genus.xls                   [属水平上的各样品表达谱总表]
│   │   ├── profiling_Species.xls                 [种水平上的各样品表达谱总表]
│   │   ├── *_StackMap                            [各分类水平上的各样品堆叠图数据]
│   │   ├── *_StackMap.pdf                        [各分类水平上的各样品堆叠图（pdf格式）]
│   │   ├── *_StackMap.png                        [各分类水平上的各样品堆叠图（png格式）]
│   │   ├── taxtree.png                           [物种分类树展示图（svg格式）]
│   │   ├── taxtree.svg                           [物种分类树展示图（svg格式）]
│   │   └── tree_stack                        [门以下分类水平物种系统发育树及各样品物种分布堆叠图]
│   │       ├── *_bar_color                       [各样品物种分布堆叠图数据]
│   │       ├── *_range                           [门一级分类水平的分类结果]
│   │       ├── *.fa                              [用于构建系统发育树的otu序列文件]
│   │       ├── *_legend.png                      [门以下分类水平物种系统发育树及各样品物种分布堆叠图（png格式）]
│   │       └── *_legend.svg                      [门以下分类水平物种系统发育树及各样品物种分布堆叠图（svg格式）]
│   └── analysis                              [各个物种分类水平上的分析]
│       ├── 1.Domain                              [界水平上的分析结果目录，文件格式同2.otu]
│       ├── 2.phylum                              [门水平上的分析结果目录，文件格式同2.otu]
│       ├── 3.Class                               [纲水平上的分析结果目录，文件格式同2.otu]
│       ├── 4.Order                               [目水平上的分析结果目录，文件格式同2.otu]
│       ├── 5.Family                              [科水平上的分析结果目录，文件格式同2.otu]
│       ├── 6.Genus                               [属水平上的分析结果目录，文件格式同2.otu]
│       └── 7.Species                             [种水平上的分析结果目录，文件格式同2.otu]
├── 4.Group_diff                          [组间差异比较结果]
│   ├── metastat                              [metastat组间差异比较结果及pathway富集分析（pathway富集分析仅限16S，ITS不做）]
│   │   ├── 1.Domain                              [界水平上的分析，如果界分类只有1个的时候不进行此分类水平分析]
│   │   │   ├── *.metastat.result.xls                 [metastat差异分析结果]
│   │   │   └── *                                     [各个比较组的Pathway富集结果]
│   │   │       ├── *.htm                                 [Pathway富集结果html报告]
│   │   │       ├── *.ko                                  [ko丰度表]
│   │   │       ├── *.path.xls                            [Pathway富集分析结果统计表]
│   │   │       ├── *.path.png                            [Pathway富集分析结果气泡图（png格式）]
│   │   │       └── *_map                                 [Pathway代谢通路图]
│   │   │           ├── *.html                                [Pathway代谢通路图（html格式）]
│   │   │           └── *.png                                 [Pathway代谢通路图（png格式）]
│   │   ├── 2.Phylum                              [门水平上的分析，内容同上]
│   │   ├── 3.Class                               [纲水平上的分析，内容同上]
│   │   ├── 4.Order                               [目水平上的分析，内容同上]
│   │   ├── 5.Family                              [科水平上的分析，内容同上]
│   │   ├── 6.Genus                               [属水平上的分析，内容同上]
│   │   └── 7.Species                             [种水平上的分析，内容同上]
│   └── LefSe                                 [LefSe多组间差异比较]
│       ├── *.Lefse.cladogram.png                 [LefSe进化分枝图（png格式）]
│       ├── *.Lefse.cladogram.svg                 [LefSe进化分枝图（svg格式）]
│       ├── *.Lefse.png                           [物种LDA柱状图（png格式）]
│       ├── *.Lefse.svg                           [物种LDA柱状图（svg格式）]
│       └── *                                     [各个比较组]
│           └── *.png                                 [单个物种在比较组中的真实表达量柱状图]
├── index.html                            [html版结题报告索引]
├── index.pdf                             [pdf版结题报告]
└── src                                   [结题报告配置文件夹]
    ├── content.html                          [结题报告主体html文件]
    ├── css                                   [css配置文件夹]
    ├── doc                                   [说明文档配置文件夹]
    ├── image                                 [图片配置文件夹]
    └── js                                    [js配置文件夹]
</pre></div>
HTML
	
	$section->menu("目录结构");
	$section->add_html($file_tree);
}

sub reference
{
	my $greengene_cite = <<TEXT;
DeSantis, T. Z., P. Hugenholtz, <i>et al.</i> (2006) <font color="#00688B">Greengenes, a Chimera-Checked 16S rRNA Gene Database and Workbench Compatible with ARB.</font> <b><i>Appl Environ Microbiol</i></b> 72:5069-72.);
TEXT
	my $unite_cite     = <<TEXT;
Kõljalg U, Nilsson RH, <i>et al.</i> (2013) <font color="#00688B">Towards a unified paradigm for sequence-based identification of Fungi</font> <b><i>Molecular Ecology</i></b> DOI: 10.1111/mec.12481;)
TEXT
	my $cite3 = $conf->{SequenceTitle} =~ /16S/i ? $greengene_cite : $unite_cite;
	
	my $ref_html = <<HTML;
<ul>
	<li><a name="cite1"></a>1. Patrick DS, Sarah LW <i>et al</i>. (2009). <font color="#00688B">Introducing  mothur:  Open-Source, Platform-Independent, Community-Supported Software for Describing and Comparing Microbial Communities.</font> <b><i>Appl Environ Microbiol</i></b>&nbsp;&nbsp;75(23):7537–7541&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#cite_back_1">BACK</a></li>
	<li><a name="cite2"></a>2. <a href="http://rdp.cme.msu.edu/classifier/classifier.jsp">http://rdp.cme.msu.edu/classifier/classifier.jsp</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#cite_back_2">BACK</a></li>
	<li><a name="cite3"></a>3. $cite3 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#cite_back_3">BACK</a></li>
	<li><a name="cite4"></a>4. M. G.I.*; Zaneveld, J.* <i>et al.</i> (2013) <font color="#00688B">Predictive functional profiling of microbial communities using 16S rRNA marker gene sequences. Langille</font>,  <b><i>Nature Biotechnology</i></b>, 1-10. 8 2013.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#cite_back_4">BACK</a></li>
	<li><a name="cite5"></a>5. Paul FK, Josephine Y A. (2010). <font color="#00688B">Bacterial diversity in aquatic and other environments: what 16S rDNA libraries can tell us.</font> <b><i>FEMS Microbiol.Ecol</i></b>&nbsp;&nbsp;47:161-177&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#cite_back_5">BACK</a></li>
	<li><a name="cite6"></a>6. Frosini BV. (2003). <font color="#00688B">Descriptive measures of ecological diversity.</font> In <i><b>Environmetrics</b></i>, A.H. El-Shaarawi and J. Jureckova (Eds.), Encyclopedia of Life Support Systems (EOLSS), EOLSS Publishers, Oxford (UK)&nbsp;&nbsp;(<a href="http://www.eolss.net">http://www.eolss.net</a>)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#cite_back_6">BACK</a></li>
	<li><a name="cite7"></a>7. Whittaker, R.H. (1960). <font color="#00688B">Vegetation of the Siskiyou mountains, Oregon and California.</font> <i><b>Ecological Monographs</b></i>&nbsp;&nbsp;30:279–338&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#cite_back_7">BACK</a></li>
	<li><a name="cite8"></a>8. <a href="http://www.is.titech.ac.jp/~shimo/prog/pvclust/">http://www.is.titech.ac.jp/~shimo/prog/pvclust/</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#cite_back_8">BACK</a></li>
</ul>
HTML
	
	my $section = shift;
	$section->menu("参考文献");
	$section->add_html($ref_html);
}

sub supplementary
{
	my $supp_heml = <<HTML;
<ul>
	<li><a href="doc/16s英文method说明文档.pdf" target="_blank">16S英文Method说明文档</a></li>
</ul>
HTML
	my $section = shift;
	$section->menu("附录");
	$section->add_html($supp_heml);
}

sub read_conf
{
	my $file = shift;
	my $conf;

	open IN,$file or die $!;
	while(<IN>)
	{
		next if (/^#/);
		chomp;
		
		if (/^\s*([^=:]+)\s*[=:]\s*(.+)\s*$/)
		{
			my ($name,$val) = ($1,$2);
			$name =~ s/\s+$//;
			$conf->{$name} = $val;
		}
	}
	close IN;
	
	return $conf;
}

sub brief_result
{
	my $dir = shift;
	my %pass = (svg=>1,png=>1,jpg=>1,tiff=>1,gif=>1,html=>1,pdf=>1);
	
	my @files;
	&fetch_all_files($dir,\@files);
	
	foreach my $file (@files)
	{
		if ($file =~ /$dir\/src/)
		{
			next;
		}
		
		unless ($file =~ /\.(\w+)$/ && $pass{$1})
		{
			unlink $file;
		}
	}
}

sub fetch_all_files
{
	my $dir = shift;
	my $files = shift;

	opendir my$DIR , $dir or die $!;

	my @list = readdir($DIR);
	foreach (@list)
	{
		next if (/^\./);
		if ( -d "$dir/$_")
		{
			fetch_all_files("$dir/$_",$files);
		}
		elsif (-e "$dir/$_")
		{
			push @$files , "$dir/$_";
		}
	}

	closedir($DIR);
}

sub fetch_best_taxon_level
{
	my $dir = shift;
	
	my $best_level;
	my $best_level_next;
	my $best_level_pre;
	my $best_level_ratio;
	my $best_level_next_ratio;
	my $order;
	
	# read the best level
	open IN,"$dir/best_level" or die $!;
	my $tmp = <IN>;
	chomp $tmp;
	close IN;
	($order,$best_level,$best_level_ratio) = split /\s+/,$tmp;
	$best_taxon = $order;
	
	# fetch the next level of best level
	open IN,"$dir/best_level_stat.xls" or die $!;
	while(<IN>)
	{
		chomp;
		my ($level,$name,$ratio) = split /\s+/;
		if ($level == $order + 1)
		{
			$best_level_next = $name;
			$best_level_next_ratio = $ratio;
		}
		elsif ($level == $order - 1)
		{
			$best_level_pre = $name;
		}
	}
	close IN;
	
	# turn float to percent
	$best_level_ratio = sprintf("%.2f%%",$best_level_ratio*100);
	$best_level_next_ratio = sprintf("%.2f%%",$best_level_next_ratio*100);
	
	# trans the English name to Chinese name
	my %trans = ("Domain"=>"界","Phylum"=>"门","Class"=>"纲","Order"=>"目","Family"=>"科","Genus"=>"属","Species"=>"种");
	$best_level = $trans{$best_level};
	$best_level_next = $trans{$best_level_next};
	$best_level_pre = $best_level_pre ? $trans{$best_level_pre} : "";

	return ($best_level,$best_level_ratio,$best_level_next,$best_level_next_ratio,$best_level_pre);
}
