#!/usr/bin/perl
#-------------------------------------------------+
#    [APM] This script was generated by amp.pl    |
#    [APM] Created time: 2016-04-27 14:29:28      |
#-------------------------------------------------+
=pod

=head1 Name

meta16S_report.pl

=head1 Synopsis

perl meta16S_report.pl [options] <pipe config file> <result dir>

=head1 Options

 -n STR    the report directory name, default use the result dir 
 -f STR    the report package format, support zip|bz2|gz|rar, default bz2

=head1 Feedback

 Author: Peng Ai
 Email : pai@genedenovo.com

=head1 Version

=head2 v1.0

Date: 2016-04-27 14:29:28

=head2 v2.0

Date: 06/05/2017 04:31:47 PM

=cut

use strict;
use warnings;
use Getopt::Std;
use File::Basename qw/basename dirname/;
use FindBin qw/$Bin/;
use Cwd 'abs_path';

use lib "$Bin/lib";
use General qw/timeLOG/;
use CONF;
use DEBUG;

use lib "/Bio/User/aipeng/bin/report/lib";
use GDHR;

my %opts = (f=>"bz2");
getopts('n:f:e',\%opts);

die `pod2text $0` unless @ARGV == 2;

# set the public var 
our ($best_taxon);

# the config file to run meta16S pipe
my $conf_file = check_path(shift @ARGV);
my $conf = load_conf($conf_file,-check=>1,-init=>1);
my @samples = split /[;,\s\t]/ , $conf->{samples};
my $sample_num = scalar @samples;

# the last result dir of meta16S pipe which will be packed and compress.
my $outdir = shift @ARGV;
my $oname  = basename($outdir);
my $resdir = dirname($outdir);
my @compares;

if ($conf->{two_groups_diff})
{
	my @temp = map {s/\&/_vs_/g; $_} split /,/,$conf->{two_groups_diff};
	splice(@compares,$#compares+1,0,@temp);
}

if ($conf->{multi_groups_diff})
{
	my @temp = map {s/\&/_vs_/g; $_} split /,/,$conf->{multi_groups_diff};
	splice(@compares,$#compares+1,0,@temp);
}

if ($opts{n})
{
	$oname = basename($opts{n});
	system("ln -sf $outdir $resdir/$oname");
	system("rm -f $outdir/upload") if (-e "$outdir/upload");
	$outdir = "$resdir/$oname";
}

# init the HTML report 
my $report = GDHR->new(-outdir=>$outdir,-pipe=>"$conf->{sequence_target} rDNA 高变区测序");

# 1. project basic information introduction
my $section = $report->section(id=>"project_info");
project_info($section);

# 2. experiment and bioinformatic analysis flow introdunction
$section = $report->section(id=>"flows");
create_tech_desc($section);

# 3. raw data deal process 
$section = $report->section(id=>"data_process");
data_process($section);

# 4. OTU cluster and analysis
$section = $report->section(id=>"otu_cluster");
otu_cluster($section);

# 5. OTU Taxonomy annot and some stat
$section = $report->section(id=>"taxonomy_annot");
taxonomy_annot($section);

# 6. alpha diversity
$section = $report->section(id=>"alpha_diversity");
alpha_diversity($section);

# 7. best diversity (sample number must > 3) 
if ($sample_num > 3)
{
	$section = $report->section(id=>"beta_diversity");
	beta_diversity($section);
}

# 8. function analysis (optional)
if ($conf->{anno_soft} ne "none")
{
	$section = $report->section(id=>"function_annot");
	function_annot($section);
}

# 9. taxonomy different analysis (optional) 
if ($conf->{two_groups_diff} || $conf->{multi_groups_diff})
{
	$section = $report->section(id=>"different_analysis");
	different_analysis($section);
}

# 10. result file tree structure 
#$section = $report->section(id=>"files_tree");
#data_save($section);

# 11. supplementary
$section = $report->section(id=>"supplementary");
supplementary($section);

# create the html file and pack the result dir.
$report->write();

exit if ($opts{e});

# move the images and help doc html files to "src" directory
if (-d "$Bin/image")
{
	system("cp -rfL $Bin/image/* $outdir/src/image");
}

if (-d "$Bin/doc")
{
	system("cp -rfL $Bin/doc/* $outdir/src/doc");
}

# trans html report to pdf 
system("sh /Bio/Bin/pipe/meta/16s/report/html2pdf.sh $outdir/src/content.html $outdir/src/content.pdf");
timeLOG("the pdf report was created");

# create brief result
system("rm -rf $resdir/${oname}_brief; cp -rL $outdir $resdir/${oname}_brief");
brief_result("$resdir/${oname}_brief");
timeLOG("the brief report was created");

if ($opts{f} eq "zip")
{
	system("cd $resdir; zip -r ${oname}_brief.zip ${oname}_brief");
}
elsif ($opts{f} eq "bz2")
{
	system("cd $resdir; tar -cjf ${oname}_brief.tar.bz2 ${oname}_brief");
}
elsif ($opts{f} eq "gz")
{
	system("cd $resdir; tar -czf ${oname}_brief.tar.gz ${oname}_brief");
}
elsif ($opts{f} eq "rar")
{
	system("cd $resdir; rar a -r ${oname}_brief.rar ${oname}_brief");
}
else 
{
	die("this package format is not support now, $opts{f} \n");
}

timeLOG("the brief report was packed");

# pack the report
$report->pack(-format=>$opts{f});

#------------------------------------------------
# sub function
#------------------------------------------------
sub project_info
{
	my $section = shift;
	my $line_num = 8;
	
	my $num = scalar @samples;
	
	my $sample_names;
	
	if ($num <= $line_num)
	{
		$sample_names .= join ("<span class=\"project_info_separator\">&brvbar;</span>", @samples);
	}
	else 
	{
		$line_num = int (($num-1)/((int( ($num-1)/$line_num) ) + 1)) + 1;
		my $i = 0;
		for ($i=0; $i < $num; $i+=$line_num )
		{
			if ($i + $line_num < $num)
			{
				my @tmp = map { $samples[$_] } $i .. $i + $line_num - 1;
				$sample_names .= join ("<span class=\"project_info_separator\">&brvbar;</span>", @tmp);
				$sample_names .= "\n\<br \/\>\n";
			}
			elsif ($i + $line_num >= $num)
			{
				my @tmp = map { $samples[$_] } $i .. $num - 1;
				$sample_names .= join ("<span class=\"project_info_separator\">&brvbar;</span>", @tmp);
			}
		}
	}
	
	my @groups = fetch_group_names($conf);
	my %groups = fetch_group_samples($conf);
	my $groups_info  = "";
	
	if ($#groups > 0)
	{
		my @groups_inner;
		foreach my$group(@groups)
		{
			my @subsamples = @{$groups{$group}};
			my $members = join "<span class=\"project_info_and\">\&</span>" , @subsamples;
			push @groups_inner , "<span class=\"project_info_group_lab\">$group :</span>$members";
		}
		
		my $info = join "<span class=\"project_info_separator\">&brvbar;</span>" , @groups_inner;
		$groups_info = "<tr><td>分组方案</td><td>$info</td></tr>"
	}
	
	my $two_diff_info = "";
	my $multi_diff_info = "";
	
	if ($conf->{two_groups_diff})
	{
		my @pairwise = map {s/\&/\-vs\-/g; $_} split /,/ , $conf->{two_groups_diff};
		my $info = join "<span class=\"project_info_separator\">&brvbar;</span>" , @pairwise;
		$two_diff_info = "<tr><td>两组差异分析方案</td><td>$info</td></tr>";
	}
	
	if ($conf->{multi_groups_diff})
	{
		my @pairwise = map {s/\&/\-vs\-/g; $_} split /,/ , $conf->{multi_groups_diff};
		my $info = join "<span class=\"project_info_separator\">&brvbar;</span>" , @pairwise;
		$multi_diff_info = "<tr><td>多组差异分析方案</td><td>$info</td></tr>";
	}
	
	my $project_info_tab = <<HTML;
<table>
<tr><td>项目编号</td><td>$conf->{"project_id"}</td></tr>
<tr><td>测序区域</td><td>$conf->{"sequence_region"}</td></tr>
<tr><td>样品信息</td><td>$sample_names</td></tr>
$groups_info
$two_diff_info
$multi_diff_info
</table>
HTML
	
	$section->menu("项目概述");
	$section->desc($project_info_tab);
}

sub create_tech_desc
{
	my $section = shift;
	
	my $primer_16s = qq(341F：<font color="red">CCTAYGGGRBGCASCAG</font>; 806R：<font color="red">GGACTACNNGGGTATCTAAT</font>);
	my $primer_ITS = qq(F：<font color="red">GCATCGATGAAGAACGCAGC</font>; R：<font color="red">ATATGTAGGATGAAGAACGYAGYRAA</font>);
	
	my $primer = $conf->{sequence_target} =~ /16S/ ? $primer_16s : $primer_ITS; 
	
	my $lab_desc = <<TEXT;
从样本中提取基因组DNA后，用带有barcode的特异引物扩增$conf->{sequence_target} rDNA的$conf->{sequence_region}区。引物序列为: 
<br />
${primer}。
<br />
然后PCR扩增产物切胶回收，用QuantiFluorTM荧光计进行定量。
将纯化的扩增产物进行等量混合，连接测序接头，构建测序文库，Hiseq2500 PE250上机测序。
TEXT
	
	my $analysis_desc = <<TEXT;
微生物多样性研究主要分为多样性研究、功能研究、样本差异比较和环境关系研究5大部分。
测序得到raw reads之后，我们对低质量reads进行过滤，然后进行组装和在过滤，以保证利用最有效数据聚类成OTU。
获得OTU后，根据分析流程，依次进行物种注释、α多样性分析、β多样性分析、PICRUSt等群落功能预测。
在存在有效分组的情况下进行组间差异比较及差异检验。最后，结合其他因素（例如环境因子），
进行特定的例如CCA等高级分析，以解答微生物与环境之间的关系。
TEXT
	
	my %introduction = (
'16S' => "16S rDNA为原核生物的核糖体特征编码序列，常用于细菌以及古细菌的物种分类以及进化关系研究。",
'18S' => "18S rDNA是编码真核生物核糖体小亚基rRNA（18S rRNA）的DNA序列，其高变序列区域则能体现物种间的差异。",
'ITS' => "真菌核糖体基因转录间隔区（internal transcribed spacer ,ITS），是位于真菌核糖体DNA（rDNA）上18S 和28S 基因之间的区域片段，主要包括ITS1和ITS2。" 
);
	
	my $tech_desc = <<TEXT;
微生物多样性测序是一种利用高通量测序技术对PCR所扩增的16S、18S、ITS等微生物物种特征序列进行检测的研究方法。
此类方法不需要对微生物进行分离纯化培养，尤其适用于环境微生物等样本的研究。<br />
$introduction{$conf->{sequence_target}}
TEXT
	
	$section->menu("技术介绍");
	$section->submenu("实验流程",-help=>"meta16S_help_v7.html#实验流程");
	$section->img2html(-file=>"image/meta16S_lab_flow.png",-name=>"实验流程图",-desc=>$lab_desc);
	#$section->desc($lab_desc);
	$section->submenu("信息分析流程");
	$section->img2html(-file=>"image/meta16S_analysis_flow_v7.png",-name=>"信息分析流程图",-desc=>$analysis_desc);
}

sub data_process
{
	my $section = shift;
	
	my $data_process_desc = <<HTML;
测序得到原始数据后，由于PCR错误、测序错误等产生大量的低质量数据或者无生物学意义数据（例如嵌合体），
因此为保证后续分析具有统计可靠性和生物学有效性，我们会在reads利用、tags拼接等
多个数据处理过程进行严格的质控，最终获得effective tags来开展后续OTU聚类等多个分析。
数据处理具体过程请参考帮助文档说明。
HTML
	
	my $filter_desc_html = <<HTML;
<p>
测序得到的原始下机数据（raw data）包含一定的低质量数据等，会影响后续的分析，因此需要对原始下机数据进行预处理。
具体的处理步骤如下：
<ul>
<li>原始数据过滤；</li>
<li>Tags拼接；</li>
<li>Tags过滤；</li>
<li>Tags去嵌合体。</li>
</ul>
为方便客户查看数据过滤情况，以了解测序与分析质量，我们严格对每一步的数据产出进行统计，结果如下表。
最终用于后续分析的为Effetive tags部分，这部分的数据一般满足3-6W条就可以进行有效分析。
</p>
HTML
	
	my $tag_abundance_desc = <<TEXT;
Tags的数目和丰度情况与测序数据量、样本类型等存在密切关系，对tag的统计有利于对样本情况进行初步判断。<br /><br />
利用 Mothur软件包对 tag 序列进行了去冗余处理，
从中挑选出 unique tag 序列（该序列实际是一组完全相同的 tag 序列的代表，
每一条 unique tag 都代表了数量不等的 tag 序列，每一条unique tag所代表的tag数即为该unique tag的丰度）。<br /><br />
去冗余前后的Tags序列统计如下所示。
<br /><br />
TEXT
	
	my $data_stat_img_desc = <<TEXT;
图片说明：reads QC filter，低质量reads；Non-overlap，
没有overlap的未组装reads；tag QC filter，未通过“tag过滤”的tags；
Chimera，嵌合体；effective tags，有效用于后续分析的tags
TEXT
	
	$section->menu("数据处理");
	$section->submenu("数据过滤及Tags拼接",-help=>"meta16S_help_v7.html#数据预处理方法");
	$section->add_html($filter_desc_html);
	$section->tsv2html(-file=>"$outdir/01.tags/02.stat/all.data_process_stat.xls",
		-name=>"数据预处理统计及质控",-header=>1,-top=>$sample_num+1,-help=>"meta16S_help_v7.html#数据预处理统计表");
	$section->img2html2(-file1 => "../01.tags/02.stat/reads_fill.png",
						-file2 => "../01.tags/02.stat/reads_stack.png",
						-name1 => "数据预处理分布图（百分比）",
						-name2 => "数据预处理分布图（数值）",
						-desc1 => $data_stat_img_desc,
						-desc2 => $data_stat_img_desc);
	
	$section->submenu("Tags丰度统计",-help=>"meta16S_help_v7.html#Tags丰度统计");
	$section->desc($tag_abundance_desc);
	$section->tsv2html(-file=>"$outdir/01.tags/02.stat/stat_tag.xls",
		-name=>"Tags 详细信息表",-header=>1,-top=>$sample_num+1,-help=>"meta16S_help_v7.html#tags-详细信息表");
	$section->tsv2html(-file=>"$outdir/01.tags/02.stat/stat_uniqTag.xls",
		-name=>"Unique Tags 详细信息表",-header=>1,-top=>$sample_num+1,-help=>"meta16S_help_v7.html#unique-tags-详细信息表");
}

sub otu_cluster
{
	my $otu_desc = <<TEXT;
OTU (Operational Taxonomic Units) 是指为了方便在系统发生学或群体遗传学研究，
人为设定的分类单元。利用effective tags之间的序列相似性关系，可以将不同的tags聚类成OTU。
获得OTU之后，利用相关软件，根据其丰度和序列信息，能够逐一开展物种注释、群落多样性、组间差异等多种核心分析。
TEXT
	my $otu_cluster_desc = <<TEXT;
<p>为了研究样品的物种的组成多样性信息，用 Uparse 软件对所有样品的全部 Effective Tags 序列聚类，
默认提供以97%的一致性(Identity)将序列聚类成为OTUs( Operational Taxonomic Units )结果，
并计算出每个OTU在各个样品中的Tags绝对丰度和相对信息。</p>
<p>在OTUs构建过程中，对不同样品的Effective Tags数据，低频数的Tags数据和Tags注释数据等信息进行初步统计，
统计结果如下图和表所示：</p>
TEXT
	
	my $otu_adu_desc = <<TEXT;
<p>OTUs的丰度信息如下表所示（其中的物种信息来自与后面物种注释）。</p>
TEXT
	
	my $otu_venn_desc = <<TEXT;
<p>不同生境下的微生物群落，其物种分布存在一定程度的相似性和特异性。
在多分组（或样本）情况下，为了解不同分组（或样本）之间的OTU差异情况，
我们可以根据OTU丰度信息开展韦恩图分析，从而了解不同样本或者分组之间的OTU的共有或者特有信息。</p>
<p>相关结果文件在目录：<a href="../02.otus/02.compare" target="_blank">02.otus/02.compare</a>下</p>
TEXT
	
	my $section = shift;
	$section->menu("OTU分析");
	$section->desc($otu_desc);
	$section->submenu("OTU聚类",-help=>"meta16S_help_v7.html#otu聚类");
	$section->desc($otu_cluster_desc);
	$section->img2html(-file=>"../02.otus/01.sequence/all.tags_otus_count.png",
					   -name=>"不同样本的OTUs和Tags数量统计图");
	$section->tsv2html(-file=>"$outdir/02.otus/01.sequence/all.tags_otus.stat.xls",-top=>$sample_num+1,
					   -name=>"不同样本的OTUs和Tags数量统计表",-help=>"meta16S_help_v7.html#tags和otus数量统计表");
	$section->desc($otu_adu_desc);
	$section->tsv2html(-file=>"$outdir/02.otus/01.sequence/all.otus.profiling.xls",
					   -name=>"OTU丰度信息表",-help=>"meta16S_help_v7.html#otu丰度信息表");
	
	
	
	if ( $conf->{two_groups_diff} || $conf->{multi_groups_diff} )
	{
		$section->submenu("OTU比较分析");
		$section->desc($otu_venn_desc);
		
		my @files = map { "../02.otus/02.compare/${_}.venn.elements.xls" } @compares;
		my @descs = map { "比较组 ${_} 中各个交并集的OTU列表文件" } @compares;
		my @imgs1 = map { "../02.otus/02.compare/${_}.venn.png" } @compares;
		my @imgs2 = map { "../02.otus/02.compare/${_}.upset.png" } @compares;
		
		$section->files2list(-files=>\@files,-desc=>\@descs);
		$section->imgs2html2(-files1=>\@imgs1,-files2=>\@imgs2,-names=>\@compares,
			-name=>"OTUs比较韦恩图",-help=>"meta16S_help_v7.html#otus比较venn图")
	}
}

sub taxonomy_annot
{
	my $section = shift;
	
	my @taxon_levels = ("Domain","Phylum","Class","Order","Family","Genus","Species");
	my @taxon_levels_chinese = ("界","门","纲","目","科","属","种");
	my $num = scalar @samples;
	my $tmp = 8 + $num;
	my $tmp1 = $tmp + 1;
	my $tmp2 = $tmp + $num;
	
	my $taxon_desc = <<TEXT;
<p>微生物物种分类一般分为界、门、纲、目、科、属、种7个等级，而每个OTU代表某类型分类水平集合。
因此根据OTU的序列信息进行物种注释，能将分析结果与实际的生物学意义进行关联，
从而研究群落中物种的变化关系等内容。</p>
<p><b>物种注释方法</b>：Uparse 在构建OTUs的过程中会选取代表性序列（OTUs中丰度最高的那条Tag序列），
将这些代表性序列集合用RDP Classifier的<b>Naïve Bayesian assignment</b>算法，
与$conf->{taxon_db}数据库进行物种注释（设定置信度的阈值为0.8~1）。</p>
<p>得到每个OTU的物种注释信息后，为了研究OTUs之前的系统发生关系，
使用 KRONA 对物种注释结果<a href ="../03.taxonomy/01.taxa_annot/all.taxonomy.krona.html" target="_blank"><b>
进行可视化展示</b></a>。圆圈从内到外依次代表不同的分类级别，扇形的大小代表不同OTU注释结果的相对比例。</p>
<p>根据OTU的物种注释信息，统计每个样品在各个分类水平（界门纲目科属种）上的Tags序列数目，
并绘制柱状图，详细信息如下所示。</p>
TEXT
	
	my $taxon_expr_desc = <<HTML;
<p><span class="bold">结合OTU的物种注释信息以及OTU在不同样品中的表达，我们按照 界->门->纲->目->科->属->种 统计了每一个分类水平上各样品的表达情况。 </span></p>
<p><span class="bold">将不同样品中属于同一物种的 Tag 数量汇总在同一个表格中，生成物种 profiling 表，如下表所示。
表中第1列是分类等级，0 表示界（Domain），1 表示门（Phylum），2 表示纲（Class），以此类推；第2至第8列是不同分类等级所对应的物种分类信息；
第9至第$tmp列表示各个样品所含的Tag序列数（物种绝对丰度）；第$tmp1列至$tmp2列是各个样品所含的Tag序列数占总Tag数的百分比（物种相对丰度）。
从这个 profiling 表中可以很容易的比较同一物种在不同样品中的丰度差异，从而找出不同样品中差异显著的物种。</span></p>
<p>结果文件在文件夹<a href="../03.taxonomy/02.taxa_profiling/" target="_blank">03.taxonomy/02.taxa_profiling</a>下：</p>
HTML
	
	my $taxon_tree_desc = <<HTML;
<p>所用软件：perl + SVG</p>
<p><span>根据物种的分类表达谱的数据，选取丰度大于<b>$conf->{min_taxtree_percent}%</b>的部分物种分类单元，
我们做出了物种分类树的展示图。如下所示：</span></p>
HTML
	
	my $taxon_tree_fig_desc = <<HTML;
说明：各个饼图中不同的颜色的区域代表不同的样品在该分类单元上的比率，半径的大小代表该分类单元所包含的tag数占总tag的比例，
半径越大代表丰度越高，饼图旁边的百分比代表该分类单元的tag数占总tag数的百分比。
HTML

	my $taxon_fill_bar = <<HTML;
<p>优势物种很大程度决定着微生物群落的生态结构以及功能结构，了解群落在各个水平的物种组成情况能有
效地对群落结构的形成、改变以及生态影响等进行解读。</p>
<p>我们统计了各个层级分类水平上的各样品的物种组成情况，然后用堆叠图的形式，
直观展示不同的样品在各个分类层级水平上的物种丰度的变化情况。</p>
<p>为了画图的美观，我们只展示至少在一个样本中的表达丰度
达到<b>$conf->{min_taxon_fill_percent}%</b>的前<b>$conf->{max_taxon_fill_number}</b>个物种，
其余物种统一归类到Other类别，无法注释到该水平的tags则被归类到Unclassified类别。</p>
<p>作图数据在目录<a href="../03.taxonomy/02.taxa_profiling" target="_blank">03.taxonomy/02.taxa_profiling</a>下：</p>
HTML
	
	my $best_taxon_level = <<HTML;
<p><span class="bold">为了确定最佳的物种分类水平，我们统计了在各个分类水平上的 tag 序列数。在进行分类分析时，
我们总是希望所得到的序列能够尽可能地注释到更低的分类等级上，但事实是，随着注释等级的降低（如从属到种），能够注释到下一等级的序列条数总是呈下降趋势。
所谓最佳分类水平，即是指分类等级尽可能低，注释上的 Tag 数量尽可能多的水平。</span></p>
HTML
	
	$section->menu("物种分类分析");
	$section->submenu("物种注释",-help=>"meta16S_help_v7.html#物种注释");
	$section->desc($taxon_desc);
	$section->tsv2html(-file=>"$outdir/03.taxonomy/01.taxa_annot/all.taxonomy.stat.xls",
					   -name=>"物种注释Tags数量统计表",-help=>"meta16S_help_v7.html#物种注释tags数量统计表");
	$section->img2html2(-file1=>"../03.taxonomy/01.taxa_annot/taxonomy_fill.png",
					   -file2=>"../03.taxonomy/01.taxa_annot/taxonomy_stack.png",
					   -name1=>"每个样品在各分类水平上的序列构成柱形图（百分比）",
					   -name2=>"每个样品在各分类水平上的序列构成柱形图（数值）");
	
	$section->submenu("物种注释表达谱");
	$section->add_html($taxon_expr_desc);
	
	my @files = qw/profiling.all.taxonomy.xls profiling.L1.Domain.xls profiling.L2.Phylum.xls profiling.L3.Class.xls profiling.L4.Order.xls profiling.L5.Family.xls profiling.L6.Genus.xls profiling.L7.Species.xls/;
	my @profiling_files = map { "../03.taxonomy/02.taxa_profiling/${_}" } @files;
	my @profiling_files_desc = ("所有分类水平上的各样品表达谱总表","界水平上的各样品表达谱总表","门水平上的各样品表达谱总表","纲水平上的各样品表达谱总表",
		"目水平上的各样品表达谱总表","科水平上的各样品表达谱总表","属水平上的各样品表达谱总表","种水平上的各样品表达谱总表");
	
	$section->files2list(-files=>\@profiling_files,-desc=>\@profiling_files_desc);
	my $allow_expr_num = 3;
	my $omits = "";
	if ($num > $allow_expr_num)
	{
		my $start1 = $allow_expr_num + 8;
		my $end1 = $num + 8;
		my $start2 = 8 + $num + $allow_expr_num;
		my $end2 = 2*$num + 8;
		
		$omits = "$start1:$end1,$start2:$end2";
	}
	$section->tsv2html(-file=>"$outdir/03.taxonomy/02.taxa_profiling/profiling.L4.Order.xls",
		-name=>"目水平上的各样品表达谱总表（前20行）",'-top'=>20,-omits=>$omits);
	
	$section->submenu("物种分类树");
	$section->add_html($taxon_tree_desc);
	$section->img2html(-file=>"../03.taxonomy/03.taxa_tree/all.samples_taxtree.png",
					   -name=>"样品的物种分类树",-help=>"meta16S_help_v7.html#物种分类树");
	$section->img2html(-file=>"../03.taxonomy/03.taxa_tree/all.groups_taxtree.png",
					   -name=>"分组的物种分类树",-help=>"meta16S_help_v7.html#物种分类树");
	
	my @taxon_fill_bar_data = map { "../03.taxonomy/02.taxa_profiling/profiling.L${[$_ + 1]}[0].$taxon_levels[$_].min2.xls" } 1 .. $#taxon_levels;
	my @taxon_fill_bar_data_desc = map { "$taxon_levels_chinese[$_]分类水平的作图数据" } 1 .. $#taxon_levels_chinese;
	my @taxon_fill_bar_imgs = map { "../03.taxonomy/04.fill_bar/$taxon_levels[$_].bar.png" } 1 .. $#taxon_levels;
	my @taxon_levels_chinese_noDomain = @taxon_levels_chinese[1 .. $#taxon_levels_chinese];
	$section->submenu("物种分布堆叠图分析");
	$section->add_html($taxon_fill_bar);
	$section->files2list(-files=>\@taxon_fill_bar_data,-desc=>\@taxon_fill_bar_data_desc);
	$section->imgs2html(-files=>\@taxon_fill_bar_imgs,-names=>\@taxon_levels_chinese_noDomain,-name=>"界以下分类水平上的物种分布堆叠图");
	
	#$section->submenu("最佳物种分类水平");
	#$section->add_html($best_taxon_level);
	#$section->tsv2html(-file=>"$outdir/03.taxonomy/05.best_level/best_level_stat.xls",-name=>"各分类水平上的Tags比例统计",
	#				   -header=>1,-top=>7);
	#$section->img2html2(-file1=>"../03.taxonomy/05.best_level/all.TagRatio.png",-file2=>"../03.taxonomy/05.best_level/all.TagNumber.png",
	#	-name1=>"样品各分类水平中 Tags 比例统计",-name2=>"样品各分类水平中 Tags 数量统计",
	#	-desc1=>"说明：横坐标是样品 ID，纵坐标是在各分类等级上所能鉴定的 tags 占总Tags的比例。",-desc2=>"说明：横坐标是样品 ID，纵坐标是在各分类等级上所能鉴定的 tags 数。");

	if ($num>=2)
	{
		my $taxon_heatmap_desc = <<HTML;
<p>所用软件：<b>R</b>语言的<b>pheatmap</b>包</p>
<p>我们根据物种分类的表达谱数据，使用热图来展示不同的物种在各样品间的表达情况，同时根据热图上的聚类关系，
也可以反映样本关系。</p>
<p>
为了减少噪音数据的影响，热图分析所挑选物种需要满足以下两个条件：<br /><br />
（1）物种在至少一个样本的相对丰度（物种tags数/总tags数）达到<b>$conf->{min_taxon_heatmap_percent}%</b>以上；<br />
（2）选取满足条件（1）的相对总丰度在前<b>$conf->{max_taxon_heatmap_number}</b>的物种进行热图分析。<br />
</p>
<p>作图所用数据在目录<a href="../03.taxonomy/02.taxa_profiling" target="_blank">03.taxonomy/02.taxa_profiling/</a>下：</p>
HTML
		
		my @heatmap_data = map { "../03.taxonomy/02.taxa_profiling/profiling.L${[$_ + 1]}[0].$taxon_levels[$_].min0.1.xls" } 1 .. $#taxon_levels; 
		my @heatmap_data_desc = map { "$taxon_levels_chinese[$_]分类水平的作图数据" } 1 .. $#taxon_levels_chinese;
		my @heatmap_names = map { $taxon_levels_chinese[$_] } 1 .. $#taxon_levels;
		my @heatmap_imgs = map { my $flag = $_ + 1; "../03.taxonomy/05.heatmap/$taxon_levels[$_].heatmap.png" } 1 .. $#taxon_levels;
		my $heatmap_desc = qq(图片说明：热图中每列代表一个样本；每行代表一个分类水平；颜色从红到蓝表示取“z-score“后丰度从高到低。);
		
		$section->submenu("物种分类热图分析");
		$section->add_html($taxon_heatmap_desc);
		$section->files2list(-files=>\@heatmap_data,-desc=>\@heatmap_data_desc);
		$section->imgs2html(-files=>\@heatmap_imgs,-names=>\@heatmap_names,
							-name=>"界以下分类水平上的物种分类热图",-note=>$heatmap_desc);
	}
}

sub alpha_diversity
{
	my $section = shift;
	
	my $otu_alpha_diversity_desc = <<HTML;
<p>我们使用QIIME软件计算alpha多样性指数，并会绘制程相应的曲线，结果见<a href="../04.alpha_diversity/01.alpha_plot/rarefaction_plots.html" target="_blank">网页</a>。</p>
HTML
	
	my $rarefaction_curve_desc = <<HTML;
<p>我们通过绘制稀释曲线（rarefaction curve）来评价测序量是否足以覆盖所有类群，并间接反映样品中物种的丰富程度。 
稀释曲线是利用已测得序列中已知的 OTU 的相对比例，来计算抽取 n 个（n 小于测得 tags 序列总数）tags 
时出现 OTU 数量的期望值， 然后根据一组 n 值（一般为一组小于总序列数的等差数列）与其相对应的 OTU 数量的
期望值做出曲线来。 当曲线趋于平缓或者达到平台期时也就可以认为测序深度已经基本覆盖到样品中所有的物种。</p>
HTML

	my $shannon_curve_desc = <<HTML;
<p>我们通过绘制shannon稀释曲线（shannon rarefaction curve）来评价测序量是否足够，并间接反映样品中物种的丰富程度。
shannon指数作为一个评价样品内物种多样性程度的指标，值越高代表多样性程度越高。
shannon稀释曲线是通过抽样n个tags来计算shannon指数的期望值，然后根据一组n值（一般为一组小于总序列数的等差数列）
与其相对应的 shannon的期望值做出曲线来，当曲线趋于平缓或者达到平台期时也就可以认为测序深度增加已经不影响物种
多样性，测序量趋于饱和。</p>
HTML
	
	my $otu_rarefaction_img_desc = <<TEXT;
说明: 图中横坐标表示抽取的 tags 数量；纵坐标表示抽取一定数量 tags 时所能得到 OTU 数量的期望值。 
TEXT
	
	my $rank_abu_desc = <<HTML;
<p>我们将样品中的OTUs按相对丰度(或者包含的序列数目)由大到小排序得到对应的排序编号，再以OTUs的排序编号为横坐标，OTUs中的相对丰度（也可用该等级OTU中序列数的相对百分含量）为纵坐标,将这些点用折线连接，即绘制得到Rank Abundance曲线。</p>
<p>Rank Abundance曲线可直观的反应样品中包含的分类丰富度和均匀度，即在水平方向，分类的丰度由曲线的宽度来反映，分类的丰富度越高，曲线在横轴上的跨度越大；在垂直方向曲线的平滑程度，反映了样品中分类的均匀程度，曲线越平缓，物种分布越均匀。</p>
HTML
	
	my $shannon_img_desc = <<TEXT;
说明：横坐标表示抽取的 tags 数量；纵坐标表示抽取一定数量 tags 时所计算得到的shannon的期望值。 
TEXT
	
	my $rank_img_desc = <<TEXT;
说明：横坐标是OTU相对丰度从大到小的排序；纵坐标表示该OTU的相对表达丰度。 
TEXT

	my $diff_alpha_desc = <<TEXT;
Alpha多样性是用来描述单个样品的物种多样性的重要参数，通过对两组或者多组间的alpha多样性进行进行假设检验，
可以分析组间的物种多样性是否存在显著的差异。我们同时使用以下几种常见的假设检验方法来进行差异分析。<br /><br />

（1）针对2个分组进行比较时，使用T-test检验和wilcox秩和检验；<br />
（2）针对2个以上分组进行比较时，使用Tukey检验和Kruskal-Wallis秩和检验。<br /><br />

<b>注：</b>上述的检验方法均要求每组至少含有3个重复样本。<br /><br />

在进行差异分析的同时，我们还绘制了各个alpha多样性指数的箱线图（下图展示了各个比较组的shannon指数箱线图）。
箱形图可以直观的反应组内物种多样性的中位数、离散程度、最大值、最小值、异常值，箱线图的详细解读可以查看<a href="https://en.wikipedia.org/wiki/Box_plot" target="_blank">wiki百科的说明</a>。<br /><br />

下表列出了差异beta多样性的综合结果，详细结果保存在目录<a href="../04.alpha_diversity/05.diff_alpha_diversity" target="_blank">04.alpha_diversity/05.diff_alpha_diversity</a>下。
TEXT
	
	$section->menu("alpha多样性分析");
	$section->submenu("alpha多样性指数统计",-help=>"meta16S_help_v7.html#alpha多样性指数统计");
	$section->add_html($otu_alpha_diversity_desc,-href=>"meta16S_help_v7.html#alpha多样性指数统计");
	$section->tsv2html(-file=>"$outdir/04.alpha_diversity/summary.alpha_diversity.xls",
					   -name=>"样品在 0.03 距离下的 Alpha 丰富程度表");
	
	$section->submenu("物种稀释曲线");
	$section->add_html($rarefaction_curve_desc);
	$section->img2html(-file=>"../04.alpha_diversity/02.rarefaction_curve/observed_speciesSampleID.png",-name=>"样品在 0.03 距离下的OTU稀释曲线图",-desc=>$otu_rarefaction_img_desc);
	
	$section->submenu("Shannon曲线");
	$section->add_html($shannon_curve_desc);
	$section->img2html(-file=>"../04.alpha_diversity/03.shannon_rarefaction_curve/shannonSampleID.png",-name=>"样品在 0.03 距离下的shannon稀释曲线图",-desc=>$shannon_img_desc);
	
	$section->submenu("Rank Abundance曲线");
	$section->add_html($rank_abu_desc);
	$section->img2html(-file=>"../04.alpha_diversity/04.otu_rank_abundance/Rank_abd_Distr.png",-name=>"样品在 0.03 距离下Rank Abundance曲线图",-desc=>$rank_img_desc);
	
	# diff alpha diversity
	if ($conf->{two_groups_diff} || $conf->{multi_groups_diff})
	{
		$section->submenu("差异alpha多样性");
		$section->desc($diff_alpha_desc);
		$section->tsv2html(-file=>"$outdir/04.alpha_diversity/05.diff_alpha_diversity/all.alpha_diversity.groups_diff.summary.xls",
						   -name=>"差异alpha多样性综合结果表",-help=>"meta16S_help_v7.html#差异多样性综合结果表",-top=>100);
		
		my @alpha_diff_names = map {s/&/-VS-/g; $_} split /\,/ , $conf->{all_pass_diffs};
		my @alpha_boxplots   = map { "../04.alpha_diversity/05.diff_alpha_diversity/shannon/${_}.boxplot.png" } @alpha_diff_names;
		$section->imgs2html(-files=>\@alpha_boxplots,
							-names=>\@alpha_diff_names,
							-name =>"各比较组shannon指数箱线图");
	}
}

sub beta_diversity
{
	my $section = shift;
	my @taxon_levels = ("Domain","Phylum","Class","Order","Family","Genus","Species");
	my @taxon_levels_chinese = ("界","门","纲","目","科","属","种");
	
	my $beta_diversity_desc = <<HTML;
<p>
Beta Diversity是对不同样品的微生物群落构成进行比较。首先根据所有样品的OTU序列，使用软件 Muscle 进行多序列比对，
然后使用软件 TreeBeST 构建OTU之间的系统发育树。
再结合OTU的丰度信息，使用R语言中的GUniFrac包来计算两两样本间的 Unweighted Unifrac 和 Weighted Unifrac距离。
最后，通过多变量统计学方法主坐标分析(PCoA，Principal Co-ordinates Analysis)，NMDS，
非加权组平均聚类分析(UPGMA，Unweighted Pair-group Method with Arithmetic Means)等分析，
进一步从结果中挖掘各样品间微生物群落结构的差异和不同分类对样品间的贡献差异。
</p>
HTML
	
	my $unifrc_desc = <<HTML;
<p>在微生物β多样性研究中，常常利用Unifrac距离衡量样本间的相似程度。
Unifrac距离计算分为物种丰度加权（weighted Unifrac）和非加权（unweighted Unifrac）两种方式，
它们数值越小，表示样本间的多样性差异性越小。利用R语言的Pheatmap包，
以热图形式展示组间weighted和unweighted Unifrac指数。如下图所示：</p>
HTML
	
	my $pca_desc = <<HTML;
<p>基于OTU列表的物种丰度信息，可以开展主成分分析（PCA，Principal Component Analysis），
从而利用利用降维的思想研究样本间的组成距离关系。这种方法借用方差分解可以有效的找出数据中最“主要”的元素和结构
，将复杂的样本组成关系反映到横纵坐标的两个特征值上，从而达到简化数据复杂度的效果。分析结果中，样品组成越相似，
反映在PCA 图中的距离越近，而且不同环境间的样品往往可能表现出各自聚集的分布情况。</p>
HTML
	
	my $pcoa_desc = <<HTML;
<p>PCoA主坐标分析是一种展示样本间相似性的分析方式，它的分析思路与PCA分析基本一致，
都是通过降维方式寻找复杂样本中的主要样本差异距离。与PCA不同的是，PCoA主要利用weighted和
unweighted Unifrac等配对信息，因此结果更集中于体现样本间的相异性距离。</p>
<p>基于样本间的weighted和unweighted Unifrac数据结果，我们可以绘制PCoA图形。分析结果中，
样品越相似，反映在PCoA 图中的距离越近，而且不同环境间的样品往往可能表现出各自聚集的分布情况。</p>
HTML
	
	my $nmds_desc = <<HTML;
<p>NMDS是非线性模型，适用于无法获得研究对象间精确的相似性或相异性数据，
其设计目的是为了克服线性模型（包括PCA、 PCoA）的缺点，更好地反映生态学数据的非线性结构。
我们根据weighted和unweighted Unifrac矩阵，进行NMDS分析。其特点是根据样品中包含的物种信息，
以点的形式反映在多维空间上，而对不同样品间的差异程度，则是通过点与点间的距离体现的，
最终获得样品的空间定位点图。</p>
HTML
	
	my $upgma_desc = <<HTML;
<p>
在微生物生态研究当中，UPGMA分类树可以用于研究样本间的相似性，解答样本的分类学问题。
利用Mothur软件，根据weighted和unweighted Unifrac矩阵信息，可以将样本进行UPGMA分类树分类。
其中越相似的样本将拥有越短的共同分支。
</p>
HTML
	
	my $diff_beta_desc = <<TEXT;
Beta多样性是用来描述两两样品间的物种多样性差异的重要参数，通过对两组或者多组内两两样品间的beta多样性
距离进行进行假设检验，可以分析不同组间的物种多样性是否存在显著的差异。
我们同时使用以下几种常见的假设检验方法来进行差异分析。<br /><br />

（1）针对2个分组进行比较时，使用T-test检验和wilcoxon秩和检验；<br />
（2）针对2个以上分组进行比较时，使用Tukey HSD检验和Kruskal-Wallis秩和检验。<br /><br />

<b>注：</b>上述的检验方法均要求每组至少含有3个重复样本。<br /><br />

在进行差异分析的同时，我们还绘制了beta多样性距离的箱线图（下图展示了各个比较组的unifrac距离箱线图）。
箱形图可以直观的反应组内物种多样性的中位数、离散程度、最大值、最小值、异常值，箱线图的详细解读可以
查看<a href="https://en.wikipedia.org/wiki/Box_plot" target="_blank">wiki百科的说明</a>。<br /><br />

下表列出了差异beta多样性的综合结果，详细结果保存在目录<a href="../05.beta_diversity/06.diff_beta_diversity" target="_blank">05.beta_diversity/06.diff_beta_diversity</a>下。
TEXT
	
	$section->menu("beta多样性分析",-help=>"meta16S_help_v7.html#beta多样性分析");
	
	$section->submenu("beta多样性指数");
	$section->add_html($unifrc_desc);
	$section->img2html2(-file1=>"../05.beta_diversity/01.unifrac/unweighted_unifrac.heatmap.png",
						-file2=>"../05.beta_diversity/01.unifrac/weighted_unifrac.heatmap.png",
						-name1=>"样本间Unweighted Unifrac指数热图",
						-name2=>"样本间Weighted Unifrac指数热图");
	
	$section->submenu("PCA分析",-help=>"meta16S_help_v7.html#pca分析");
	$section->desc($pca_desc);
	$section->img2html2(-file1=>"../05.beta_diversity/02.PCA/all.otus.exp_for_unifrac.PCA2D.png",
						-file2=>"../05.beta_diversity/02.PCA/all.otus.exp_for_unifrac.PCA3D.png",
						-name1=>"2D OTU PCA plot",-name2=>"3D OTU PCA plot");
	
	$section->submenu("PCoA分析",-help=>"meta16S_help_v7.html#pcoa分析");
	$section->add_html($pcoa_desc);
	$section->img2html2(-file1=>"../05.beta_diversity/03.PCoA/unweighted_unifrac.PCoA.png",
						-file2=>"../05.beta_diversity/03.PCoA/weighted_unifrac.PCoA.png",
						-name1=>"基于unweighted Unifrac距离的PCoA分析",
						-name2=>"基于weighted Unifrac距离的PCoA分析");
	
	$section->submenu("NMDS分析",-help=>"meta16S_help_v7.html#nmds分析");
	$section->add_html($nmds_desc);
	$section->img2html2(-file1=>"../05.beta_diversity/04.NMDS/unweighted_unifrac.NMDS.png",
						-file2=>"../05.beta_diversity/04.NMDS/weighted_unifrac.NMDS.png",
						-name1=>"基于unweighted Unifrac距离的NMDS分析",
						-name2=>"基于weighted Unifrac距离的NMDS分析");
	
	my @unweighted_imgs = map { "../05.beta_diversity/05.UPGMA/unweighted.$taxon_levels[$_].UPGMA_stack.png" } 1 .. $#taxon_levels;
	my @weighted_imgs   = map { "../05.beta_diversity/05.UPGMA/weighted.$taxon_levels[$_].UPGMA_stack.png" } 1 .. $#taxon_levels;
	my @upgma_names = map { $taxon_levels_chinese[$_] } 1 .. $#taxon_levels;

	
	$section->submenu("UPGMA聚类分析",-help=>"meta16S_help_v7.html#upgma聚类分析");
	$section->add_html($upgma_desc);
	$section->imgs2html(-files=>\@unweighted_imgs,-names=>\@upgma_names,
						 -name=>"基于Unweighted Unifrac距离的UPGMA聚类树");
	$section->imgs2html(-files=>\@weighted_imgs,-names=>\@upgma_names,
						 -name=>"基于Weighted Unifrac距离的UPGMA聚类树");
						 
	# diff alpha diversity
	if ($conf->{two_groups_diff} || $conf->{multi_groups_diff})
	{
		$section->submenu("差异beta多样性");
		$section->desc($diff_beta_desc);
		$section->tsv2html(-file=>"$outdir/05.beta_diversity/06.diff_beta_diversity/all.beta_diversity.groups_diff.summary.xls",
						   -name=>"差异beta多样性综合结果表",-help=>"meta16S_help_v7.html#差异多样性综合结果表",
						   -top=>100);
		
		my @beta_diff_names = map {s/&/-VS-/g; $_} split /\,/ , $conf->{all_pass_diffs};
		my @uwf_boxplots    = map { "../05.beta_diversity/06.diff_beta_diversity/unweighted_unifrac/${_}.boxplot.png" } @beta_diff_names;
		my @wf_boxplots     = map { "../05.beta_diversity/06.diff_beta_diversity/weighted_unifrac/${_}.boxplot.png" } @beta_diff_names;
		$section->imgs2html2(-files1=>\@uwf_boxplots,
							 -files2=>\@wf_boxplots,
							 -names =>\@beta_diff_names,
							 -name  =>"各比较组unifrac距离箱线图",
							 -note  =>"说明：左边的unweighted unifrac箱线图，右边的是weighted unifrac箱线图");
		
		# Anosim & Adonis
		$section->submenu("Anosim,Adonis差异分析");
	}
}

sub function_annot
{
	my $section = shift;
	
	my $picrust_pathway_desc = <<HTML;
<p>根据OTU的物种注释和丰度信息，使用PICRUSt软件可以进行KEGG Pathway的功能注释，并统计每个Pathway和KO id的丰度信息。
详细结果如下表所示。</p>
HTML
	
	$section->menu("功能注释分析");
	
	
	if ($conf->{anno_soft} =~ /PICRUSt/i)
	{
		$section->submenu("OTU Pathway 注释",-help=>"meta16S_help_v7.html#pathway注释");
		$section->add_html($picrust_pathway_desc,-help=>"meta16S_help_v7.html#picrust");
		$section->tsv2html(-file=>"$outdir/06.function_annot/1.annot_result/all.ko.annot.xls",
					   -name=>"Pathway D级分类注释表（前20行）",-top=>20);
		$section->tsv2html(-file=>"$outdir/06.function_annot/1.annot_result/all.pathway.annot.xls",
					   -name=>"Pathway C级分类注释表（前20行）",-top=>20);
		$section->tsv2html(-file=>"$outdir/06.function_annot/1.annot_result/all.ko.NSTI.xls",
					   -name=>"PICRUSt软件NSTI打分表",-top=>$sample_num);
	}
	elsif ($conf->{anno_soft} =~ /Tax4Fun/i)
	{
		$section->submenu("OTU Pathway 注释",-help=>"meta16S_help_v7.html#pathway注释");
		
	}
	elsif ($conf->{anno_soft} =~ /FUNGuild/i)
	{
		$section->submenu("OTU Pathway 注释",-help=>"meta16S_help_v7.html#guild注释");
	}
}

sub different_analysis
{
	my @taxon_levels = ("Domain","Phylum","Class","Order","Family","Genus","Species");
	my @taxon_levels_chinese = ("界","门","纲","目","科","属","种");
	my $num = scalar @samples;
	
	$section->menu("物种差异分析");
	
	if ($conf->{two_groups_diff})
	{
		my $taxon_diff_desc = <<HTML;
<p>通过统计学的方法（Metastats软件）检验两组样品间微生物群落丰度的差异，得到p值，然后使用FDR对p值进行校正得到q值，
最后通过对p值或者q值的筛选来评估差异的显著性，找出导致两组样品组成差异的物种。</p>
<p>结果文件保存在目录<a href="../07.taxa_diff/metastat" target="_blank">07.taxa_diff/metastat</a>下。
差异分析的结果如下表所示：</p>
HTML
		
		$section->submenu("Metastats",-help=>"meta16S_help_v7.html#metastats");
		$section->add_html($taxon_diff_desc);
		
		# print the result file list 
		my @groups = split /,/,$conf->{two_groups_diff};
		foreach my $group (@groups)
		{
			$group =~ s/&/-VS-/;
			my @result_files;
			my @result_files_desc;
			
			foreach (0 .. $#taxon_levels)
			{
				my$flag = $_+1;
				if (-e "$outdir/07.taxa_diff/metastat/${flag}.$taxon_levels[$_]/$group.metastat.result.xls")
				{
					push @result_files , "../07.taxa_diff/metastat/$flag.$taxon_levels[$_]/$group.metastat.result.xls";
					push @result_files_desc , "$taxon_levels_chinese[$_]分类水平上的差异分析结果";
				}
			}
			
			#$section->desc("<b>$group</b>在各分类水平上的差异分析结果：");
			#$section->files2list(-files=>\@result_files,-desc=>\@result_files_desc);
		}
		
		# add the demo table (Class level)
		my $frt_group = $groups[0];
		my $result = "$outdir/07.taxa_diff/metastat/3.Class/$frt_group.metastat.result.xls";
		my $name = "<b>$frt_group</b>在纲分类水平下的差异分析结果";
		$section->desc("下表是<b>$frt_group</b>在门分类水平下的差异分析结果：");
		$section->tsv2html(-file=>$result,-name=>$name,-top=>20);
		
		# pathway 富集分析 , just for 16S (discard for meta16S pipeline v7)
		if ($conf->{"sequence_target"} =~ /16S/i && 0 == 1)
		{
			my $pathway_enrich_desc = <<HTML;
通过metastat分析以后，筛选出|Log2(FC)|>=1 以及Pvalue<=0.05 显著差异物种，并对其进行富集分析。
HTML
		
			my $pathway_enrich_bubble_desc = <<HTML;
根据富集分析的结果，我们根据qvalue值，选取显著性最高的前20个通路绘制KEGG pathway气泡图，如下所示：
HTML
	
			$section->submenu("各分类水平上的组间差异Pathway功能分析");
			$section->desc($pathway_enrich_desc,-help=>"meta16S_help_v7.html#富集分析");
			$section->add_html($pathway_enrich_bubble_desc);
		
			foreach my $group (@groups)
			{
				my @pathway_enrich_bubble_imgs;
				my @pathway_enrich_bubble_names;

				foreach (0 .. $#taxon_levels) 
				{
					my $flag = $_ + 1;
					my $file = "$outdir/4.Group_diff/metastat/$flag.$taxon_levels[$_]/$group/$group.path.png";
					if (-e $file)
					{ 
						push @pathway_enrich_bubble_imgs , "../4.Group_diff/metastat/$flag.$taxon_levels[$_]/$group/$group.path.png";
						push @pathway_enrich_bubble_names , $taxon_levels_chinese[$_];
					}
				}
			
				next if ($#pathway_enrich_bubble_imgs == -1);
			
				my $name = "<font color=\"red\">$group</font>在各个分类水平上的Pathway富集分析气泡图";
				my $note = <<TEXT;
说明：图中x轴为RichFactor，等于差异的物种分类对应的K号/全部的物种分类对应的K；y轴为代谢图路；
点的大小表示注释上该通路中的全部物种分类数；点的颜色表示Qvalue的大小。
TEXT
				$section->imgs2html(-files=>\@pathway_enrich_bubble_imgs,-names=>\@pathway_enrich_bubble_names,-name=>$name,-note=>$note);
				$section->add_html("<br /><br />");
			}
		}
	}
	
	if ($conf->{multi_groups_diff} || $conf->{two_groups_diff})
	{
		my $lefse_desc = <<HTML;
<p>通过LEFse分析组间菌群差异，可以找出各组间特异的主要菌群，有助于开发biomaker等研究。</p>
<p>利用LEFse软件对差异组间进行分析，LEFse先对所有组样品间进行kruskal-Wallis秩和检验（一种多样本比较时常用的检验方法），
将筛选出的差异再通过wilcoxon秩和检验（一种两样本成组比较常用的检验方法）进行两两组间比较，最后筛选出的差异使用LDA（Linear Discriminant Analysis）
得出的结果进行排序得到左图，左图展示了不同组中丰度差异显著的物种，柱状图的长度代表差异物种的影响大小（即为LDA Score）。
随后通过将差异映射到已知层级结构的分类树上方式得到进化分支图(右图)。在进化分支图中，由内至外辐射的圆圈代表了由门至属（或种）的分类级别。
在不同分类级别上的每一个小圆圈代表该水平下的一个分类，小圆圈直径大小与相对丰度大小呈正比。着色原则：无显著差异的物种统一着色为黄色。详细见下图：</p>
HTML

		my @vses1 = split /,/,$conf->{multi_groups_diff};
		my @vses2 = split /,/,$conf->{two_groups_diff};
		my @groups = grep { -e "$outdir/07.taxa_diff/Lefse/${_}.Lefse.svg" } map {s/&/-vs-/g; $_} (@vses1,@vses2);
		return unless @groups;
		
		$section->submenu("Lefse分析",-help=>"meta16S_help_v7.html#lefse");
		$section->add_html($lefse_desc);
		
		my @imgs1 = map { "../07.taxa_diff/Lefse/${_}.Lefse.png" } @groups;
		my @imgs2 = map { "../07.taxa_diff/Lefse/${_}.Lefse.cladogram.png" } @groups;
		
		$section->imgs2html2(-files1=>\@imgs1,-files2=>\@imgs2,-names=>\@groups,-name=>"LEFse差异分析图");
		
		#$section->desc("LEFse还提供单个差异物种在各个比较组的真实表达量图，见下图：");
		foreach my$group (@groups)
		{
			my @single_taxon_imgs;
			my @names;
			
			my @tmp_files = glob("$outdir/07.taxa_diff/Lefse/$group/*.png");
			
			foreach (@tmp_files)
			{
				my$fname = basename($_); 
				push @single_taxon_imgs , "../07.taxa_diff/Lefse/$group/$fname";
				
				$fname =~ s/\.png//;
				push @names , $fname;
			}
			
			my $name = "单个物种在比较组 <font color=\"red\">$group</font> 中的真实表达量图(部分)";
			
			@single_taxon_imgs = @single_taxon_imgs[0 .. 9] if($#single_taxon_imgs > 9);
			@names = @names[0 .. 9] if ($#names > 9);
			#$section->imgs2html(-files=>\@single_taxon_imgs,-names=>\@names,-name=>$name);
		}
	}
}

sub data_save
{
	my $section = shift;
	
	my $file_tree = <<HTML;
<div><pre>
result_root_dir
├── 1.tag                                 [tags结果]
│   ├── fasta                                 [各样品的tags序列]
│   │   └── *.fasta                               [各样品的tags序列文件(fasta格式)]
│   └── stat                                  [各样品tags序列统计结果]
│       ├── stat_tag.xls                          [各样品tags序列统计]
│       ├── stat_uniqTag.xls                      [各样品unique tags序列统计]
│       ├── tagAbdDistr                           [各样品的tag序列的丰度分布]
│       ├── tagAbdDistr.pdf                       [各样品的tag序列的丰度分布统计图(pdf格式)]
│       ├── tagAbdDistr.png                       [各样品的tag序列的丰度分布统计图(png格式)]
│       ├── tagLenDistr                           [各样品的tag序列的长度分布统计]
│       ├── tagLenDistr.pdf                       [各样品的tag序列的长度分布统计图(pdf格式)]
│       └── tagLenDistr.png                       [各样品的tag序列的长度分布统计图(png格式)]
├── 2.otu                                 [otu结果]
│   ├── analysis                              [otu高级分析结果]
│   │   ├── otu.rarefaction                       [OTU的稀释曲线数据]
│   │   ├── otu.rarefaction.pdf                   [OTU的稀释曲线的分布图（pdf格式）]
│   │   ├── otu.rarefaction.png                   [OTU的稀释曲线的分布图（png格式）]
│   │   ├── shannon.rarefaction                   [shannon稀释曲线数据]
│   │   ├── shannon.rarefaction.pdf               [shannon稀释曲线的分布图（pdf格式）]
│   │   ├── shannon.rarefaction.png               [shannon稀释曲线的分布图（png格式）]
│   │   ├── alpha_diversity_total.xls             [alpha多样性的统计总表]
│   │   ├── alpha_diversity_short.xls             [alpha多样性的统计简表]
│   │   ├── otu_exp.filter                        [过滤掉表达量小于0.1%的OTU后，剩下的OTU表达谱，是后续作图分析的输入数据]
│   │   ├── otu_exp.filter.matrix                 [beta多样性的矩阵]
│   │   ├── otu_exp.filter.betadiversity.pdf      [beta多样性图（pdf格式）]
│   │   ├── otu_exp.filter.betadiversity.png      [beta多样性图（png格式）]
│   │   ├── otu_exp.filter.heatmap.pdf            [otu表达谱热图（pdf格式）]
│   │   ├── otu_exp.filter.heatmap.png            [otu表达谱热图（png格式）]
│   │   ├── otu_exp.filter.colm.bray.pdf          [bray-curtis系数聚类图（pdf格式）]
│   │   ├── otu_exp.filter.colm.bray.png          [bray-curtis系数聚类图（png格式）]
│   │   ├── otu_exp.filter.PCA2D.pdf              [PCA图（2D）（pdf格式）]
│   │   ├── otu_exp.filter.PCA2D.png              [PCA图（2D）（png格式）]
│   │   ├── otu_exp.filter.PCA3D.pdf              [PCA图（3D）（pdf格式）]
│   │   ├── otu_exp.filter.PCA3D.png              [PCA图（3D）（png格式）]
│   │   ├── otu_exp.filter.PCA2D.nonames.pdf      [PCA图（2D）（pdf格式）（无样品名）]
│   │   ├── otu_exp.filter.PCA2D.nonames.png      [PCA图（2D）（png格式）（无样品名）]
│   │   ├── otu_exp.filter.PCA3D.nonames.pdf      [PCA图（3D）（pdf格式）（无样品名）]
│   │   ├── otu_exp.filter.PCA3D.nonames.png      [PCA图（3D）（png格式）（无样品名）]
│   │   ├── otu_exp.filter.PCA.samples.xls        [PCA分析中每个样品的坐标]
│   │   ├── otu_exp.filter.PCA.component.xls      [PCA分析中每个OTU的坐标]
│   │   ├── otu_exp.filter.kld_jsd.newick         [cluser图中的样品关系树文件]
│   │   ├── otu_exp.filter.kld_jsd.pdf            [cluster图（pdf格式）]
│   │   └── otu_exp.filter.kld_jsd.png            [cluster图（pdf格式）]
│   ├── annot                                 [otu pathway注释（仅16S的项目进行此项分析，ITS的没有）]
│   │   ├── meta_ko_annot.xls                     [otu pathway注释总表]
│   │   └── Sample                                [各样品otu pathway注释结果]
│   │       ├── *.path.xls                            [各样品的OTU Pathway注释结果统计表]
│   │       ├── *.png                                 [各样品的OTU Pathway注释结果统计图（png格式）]
│   │       └── *.svg                                 [各样品的OTU Pathway注释结果统计图（svg格式）]
│   ├── expression_profile                    [表达谱结果]
│   │   ├── otu.profile.xls                       [OTU的表达谱]
│   │   └── otu.representative.fasta              [每个OTU的代表性序列]
│   └── stat                                  [otu统计结果]
│       ├── stat_otu.xls                          [各样品otu数量统计]
│       ├── otuAbdDistr                           [各样品的otu的丰度分布]
│       ├── otuAbdDistr.pdf                       [各样品的otu的丰度分布统计图（pdf格式）]
│       └── otuAbdDistr.png                       [各样品的otu的丰度分布统计图（png格式）]
├── 3.taxa                                [物种分类结果]
│   ├── stat                                  [物种分类结果统计]
│   │   ├── wholeTaxStat                          [各分类水平上tags数量统计]
│   │   ├── wholeTaxStat.TagNumber.pdf            [各分类水平上tags数量统计图（pdf格式）]
│   │   ├── wholeTaxStat.TagNumber.png            [各分类水平上tags数量统计图（png格式）]
│   │   ├── wholeTaxStat.TagRatio.pdf             [各分类水平上tags比例统计图（pdf格式）]
│   │   ├── wholeTaxStat.TagRatio.png             [各分类水平上tags比例统计图（png格式）]
│   │   ├── best_level                            [最佳分类水平]
│   │   └── best_level_stat.xls                   [不同分类水平上的比例统计]
│   ├── expression_profile                    [物种分类表达谱结果]
│   │   ├── profiling_all.xls                     [所有分类水平上的各样品表达谱总表]
│   │   ├── profiling_Domain.xls                  [界水平上的各样品表达谱总表]
│   │   ├── profiling_Phylum.xls                  [门水平上的各样品表达谱总表]
│   │   ├── profiling_Class.xls                   [纲水平上的各样品表达谱总表]
│   │   ├── profiling_Order.xls                   [目水平上的各样品表达谱总表]
│   │   ├── profiling_Family.xls                  [科水平上的各样品表达谱总表]
│   │   ├── profiling_Genus.xls                   [属水平上的各样品表达谱总表]
│   │   ├── profiling_Species.xls                 [种水平上的各样品表达谱总表]
│   │   ├── *_StackMap                            [各分类水平上的各样品堆叠图数据]
│   │   ├── *_StackMap.pdf                        [各分类水平上的各样品堆叠图（pdf格式）]
│   │   ├── *_StackMap.png                        [各分类水平上的各样品堆叠图（png格式）]
│   │   ├── taxtree.png                           [物种分类树展示图（svg格式）]
│   │   ├── taxtree.svg                           [物种分类树展示图（svg格式）]
│   │   └── tree_stack                        [门以下分类水平物种系统发育树及各样品物种分布堆叠图]
│   │       ├── *_bar_color                       [各样品物种分布堆叠图数据]
│   │       ├── *_range                           [门一级分类水平的分类结果]
│   │       ├── *.fa                              [用于构建系统发育树的otu序列文件]
│   │       ├── *_legend.png                      [门以下分类水平物种系统发育树及各样品物种分布堆叠图（png格式）]
│   │       └── *_legend.svg                      [门以下分类水平物种系统发育树及各样品物种分布堆叠图（svg格式）]
│   └── analysis                              [各个物种分类水平上的分析]
│       ├── 1.Domain                              [界水平上的分析结果目录，文件格式同2.otu]
│       ├── 2.phylum                              [门水平上的分析结果目录，文件格式同2.otu]
│       ├── 3.Class                               [纲水平上的分析结果目录，文件格式同2.otu]
│       ├── 4.Order                               [目水平上的分析结果目录，文件格式同2.otu]
│       ├── 5.Family                              [科水平上的分析结果目录，文件格式同2.otu]
│       ├── 6.Genus                               [属水平上的分析结果目录，文件格式同2.otu]
│       └── 7.Species                             [种水平上的分析结果目录，文件格式同2.otu]
├── 4.Group_diff                          [组间差异比较结果]
│   ├── metastat                              [metastat组间差异比较结果及pathway富集分析（pathway富集分析仅限16S，ITS不做）]
│   │   ├── 1.Domain                              [界水平上的分析，如果界分类只有1个的时候不进行此分类水平分析]
│   │   │   ├── *.metastat.result.xls                 [metastat差异分析结果]
│   │   │   └── *                                     [各个比较组的Pathway富集结果]
│   │   │       ├── *.htm                                 [Pathway富集结果html报告]
│   │   │       ├── *.ko                                  [ko丰度表]
│   │   │       ├── *.path.xls                            [Pathway富集分析结果统计表]
│   │   │       ├── *.path.png                            [Pathway富集分析结果气泡图（png格式）]
│   │   │       └── *_map                                 [Pathway代谢通路图]
│   │   │           ├── *.html                                [Pathway代谢通路图（html格式）]
│   │   │           └── *.png                                 [Pathway代谢通路图（png格式）]
│   │   ├── 2.Phylum                              [门水平上的分析，内容同上]
│   │   ├── 3.Class                               [纲水平上的分析，内容同上]
│   │   ├── 4.Order                               [目水平上的分析，内容同上]
│   │   ├── 5.Family                              [科水平上的分析，内容同上]
│   │   ├── 6.Genus                               [属水平上的分析，内容同上]
│   │   └── 7.Species                             [种水平上的分析，内容同上]
│   └── LefSe                                 [LefSe多组间差异比较]
│       ├── *.Lefse.cladogram.png                 [LefSe进化分枝图（png格式）]
│       ├── *.Lefse.cladogram.svg                 [LefSe进化分枝图（svg格式）]
│       ├── *.Lefse.png                           [物种LDA柱状图（png格式）]
│       ├── *.Lefse.svg                           [物种LDA柱状图（svg格式）]
│       └── *                                     [各个比较组]
│           └── *.png                                 [单个物种在比较组中的真实表达量柱状图]
├── index.html                            [html版结题报告索引]
├── index.pdf                             [pdf版结题报告]
└── src                                   [结题报告配置文件夹]
    ├── content.html                          [结题报告主体html文件]
    ├── css                                   [css配置文件夹]
    ├── doc                                   [说明文档配置文件夹]
    ├── image                                 [图片配置文件夹]
    └── js                                    [js配置文件夹]
</pre></div>
HTML
	
	$section->menu("目录结构");
	$section->add_html($file_tree);
	
}

sub supplementary
{
	my $supp_html = <<HTML;
<ul>
	<li><a href="doc/meta16S_help_v7.html#主要软件数据库及版本信息" target="_blank">主要软件数据库及版本信息</a></li>
	<li><a href="doc/16s英文method说明文档.pdf" target="_blank">16S英文Method说明文档</a></li>
</ul>
HTML
	my $section = shift;
	$section->menu("附录");
	$section->add_html($supp_html);
}

sub brief_result
{
	my $dir = shift;
	my %pass = (svg=>1,png=>1,jpg=>1,tiff=>1,gif=>1,html=>1,pdf=>1);
	
	my @files;
	&fetch_all_files($dir,\@files);
	
	foreach my $file (@files)
	{
		if ($file =~ /$dir\/src/)
		{
			next;
		}
		
		unless ($file =~ /\.(\w+)$/ && $pass{$1})
		{
			unlink $file;
		}
	}
}

sub fetch_all_files
{
	my $dir = shift;
	my $files = shift;

	opendir my$DIR , $dir or die $!;

	my @list = readdir($DIR);
	foreach (@list)
	{
		next if (/^\./);
		if ( -d "$dir/$_")
		{
			fetch_all_files("$dir/$_",$files);
		}
		elsif (-e "$dir/$_")
		{
			push @$files , "$dir/$_";
		}
	}

	closedir($DIR);
}

sub fetch_best_taxon_level
{
	my $dir = shift;
	
	my $best_level;
	my $best_level_next;
	my $best_level_pre;
	my $best_level_ratio;
	my $best_level_next_ratio;
	my $order;
	
	# read the best level
	open IN,"$dir/best_level" or die $!;
	my $tmp = <IN>;
	chomp $tmp;
	close IN;
	($order,$best_level,$best_level_ratio) = split /\s+/,$tmp;
	$best_taxon = $order;
	
	# fetch the next level of best level
	open IN,"$dir/best_level_stat.xls" or die $!;
	while(<IN>)
	{
		chomp;
		my ($level,$name,$ratio) = split /\s+/;
		if ($level == $order + 1)
		{
			$best_level_next = $name;
			$best_level_next_ratio = $ratio;
		}
		elsif ($level == $order - 1)
		{
			$best_level_pre = $name;
		}
	}
	close IN;
	
	# turn float to percent
	$best_level_ratio = sprintf("%.2f%%",$best_level_ratio*100);
	$best_level_next_ratio = sprintf("%.2f%%",$best_level_next_ratio*100);
	
	# trans the English name to Chinese name
	my %trans = ("Domain"=>"界","Phylum"=>"门","Class"=>"纲","Order"=>"目","Family"=>"科","Genus"=>"属","Species"=>"种");
	$best_level = $trans{$best_level};
	$best_level_next = $trans{$best_level_next};
	$best_level_pre = $best_level_pre ? $trans{$best_level_pre} : "";

	return ($best_level,$best_level_ratio,$best_level_next,$best_level_next_ratio,$best_level_pre);
}
