#!/usr/bin/perl
#-------------------------------------------------+
#    [APM] This script was generated by amp.pl    |
#    [APM] Created time: 2015-12-17 09:55:04      |
#-------------------------------------------------+
# name: run_krona.pl
# func: 1. split the all profiliing file to fragment for each sample 
#       2. run krona to create the multi level pie chart (html file)
# version:: 0.1

use strict;
use warnings;

use FindBin qw/$Bin/;
use Cwd 'abs_path';

use lib "$Bin/../lib/";
use CONF qw/load_conf fetch_path/;

my $conf = load_conf("$Bin/../etc/software.conf");
my $krona = fetch_path($conf,"krona");

die "Usage: perl $0 <all.profiliing.xls>\n" unless @ARGV == 1;

my $file = shift @ARGV;

open IN,$file or die $!;
my$header = <IN>;
chomp $header;
close IN;

my @temp = split /\t/,$header;
my $len = scalar @temp;
my $taxon_start = $len - 7 + 1;

my $sample_end = $len - 7;
my $sample_sta = 2;
my $sample_num = ($sample_end - $sample_sta + 1) / 2;

my @samples;
for ( my$i=$sample_sta;$i<=$sample_sta+$sample_num-1;$i++ )
{
	my $sample = $temp[$i-1];
	$sample =~ s/\_tags$//;
	push @samples , $sample;
	system("cut -f $i,$taxon_start-$len $file | awk 'NR>1' > $sample.profiliing.tsv");
}

my @files = map { "$_.profiliing.tsv" } @samples;
my $str = join " " , @files;

system("perl $krona $str -n Root -o all.taxonomy.krona.html");
# system("rm -f $str");
