#!/usr/bin/perl
#-------------------------------------------------+
#    [APM] This script was generated by amp.pl    |
#    [APM] Created time: 2016-05-19 14:38:25      |
#-------------------------------------------------+
# name: wholeTaxStat.pl
# func: 
# version: 0.1

use strict;
use warnings;
use File::Basename qw/basename/;
use List::Util qw/sum/;

die qq(
Usage: perl $0 <wholeTaxStat> [stat_tag.xls]
\n) if (@ARGV != 1 && @ARGV != 2);

my $file = shift @ARGV;
my $all_tag = shift @ARGV;

# read the all Tag number of all samples 
my %tags;
if ($all_tag)
{
	open IN,$all_tag or die $!;
	<IN>;
	while(<IN>)
	{
		my ($sample,$num) = (split /\t/)[0,1];
		$tags{$sample} = $num;
	}
	close IN;
}

open IN,$file or die $!;
open OUT1,">all.TagNumber.forGGPLOT" or die $!;
open OUT2,">all.TagRatio.forGGPLOT" or die $!;
open OUT3,">best_level_stat.xls" or die $!;

my $head = <IN>;
chomp $head;
my ($tmp,@levels) = split /\s+/,$head;

print OUT1 "Samples\tTaxonomy\tTaxonName\tTagNumber\n";
print OUT2 "Samples\tTaxonomy\tTaxonName\tTagRatio\n";

my %stat;
my $sum;
while(<IN>)
{
	chomp;
	my ($sample,@number) = split /\t/;
	
	for (0 .. $#levels)
	{
		print OUT1 "$sample\t${_}_$levels[$_]\t$levels[$_]\t$number[$_]\n";
		
		my $ratio = $tags{$sample} ? $number[$_]/$tags{$sample} : $number[$_]/$number[0];
		print OUT2 "$sample\t${_}_$levels[$_]\t$levels[$_]\t$ratio\n";

		$stat{"${_}_$levels[$_]"}{num} += $number[$_];
	}
	$sum += $tags{$sample} ? $tags{$sample} : $number[0];
}

my $flag = 0;
print OUT3 "Taxonomy Order\tTaxonomy Level\tAnnot Ratio\tSignature\n";
foreach my $taxon (sort {$b cmp $a} keys %stat)
{
	my ($level,$name) = split /_/ , $taxon;
	my $ratio = $stat{$taxon}{num} / $sum;
	
	if ($ratio > 0.45 && $flag == 0)
	{
		print OUT3 "$level\t$name\t$ratio\tbest_level\n";
		$flag = 1;
	}
	else 
	{
		print OUT3 "$level\t$name\t$ratio\n";
	}
}

close IN;
close OUT1;
close OUT2;
close OUT3;

my $Rcmd = <<CMD;
library(ggplot2)

# the function to get colors 
gg_color_hue <- function(n) {
	hues = seq(15, 375, length = n + 1)
	hcl(h = hues, l = 65, c = 100)[1:n]
}

data = read.table("all.TagNumber.forGGPLOT",header=T)
porder = factor(data\$Samples,levels=unique(data\$Samples),order=TRUE)
sample_num = length(unique(data\$Samples))
if (sample_num < 6){sample_num = 6}

num = ggplot(data,aes(porder,TagNumber)) + 
geom_bar(stat="identity",aes(fill=Taxonomy),position="dodge",color="black") + 
scale_fill_manual(values=gg_color_hue(7),labels=data[1:7,]\$TaxonName) + 
guides(fill = guide_legend(nrow = 1)) +
labs(x="Samples",y="Number of Annotated Tags") + 
theme(legend.position="top",axis.text.x=element_text(angle=45,vjust=1,hjust=1))
ggsave("all.TagNumber.png",num,width=sample_num,height=7)
ggsave("all.TagNumber.pdf",num,width=sample_num,height=7)
ggsave("all.TagNumber.fix.png",num,width=10,height=7)

ratio = read.table("all.TagRatio.forGGPLOT",header=T)
porder = factor(ratio\$Samples,levels=unique(ratio\$Samples),order=TRUE)
sample_num = length(unique(ratio\$Samples))
if (sample_num < 6){sample_num = 6}

num = ggplot(ratio,aes(porder,TagRatio)) + 
geom_bar(stat="identity",aes(fill=Taxonomy),position="dodge",color="black") + 
scale_fill_manual(values=gg_color_hue(7),labels=ratio[1:7,]\$TaxonName) + 
guides(fill = guide_legend(nrow = 1)) +
labs(x="Samples",y="Ratio of Annotated Tags") + 
theme(legend.position="top",axis.text.x=element_text(angle=45,vjust=1,hjust=1))
ggsave("all.TagRatio.png",num,width=sample_num,height=7)
ggsave("all.TagRatio.pdf",num,width=sample_num,height=7)
ggsave("all.TagRatio.fix.png",num,width=10,height=7)

CMD

open R,">tmp.R" or die $!;
print R $Rcmd;
close R;

system("Rscript tmp.R");
